### ISSUE TITLE
Namespace problem

### ISSUE THREAD

**Issue by fdcastel** [fsprojects/Fable#101]
This code compiles ok:

```fsharp
namespace Test.MyNamespace

module MyModule =

    type MyType =
        | SomeInt of int
        | SomeString of string
        | None

    type MyClass() = 

        let letValue = 3
        member this.memberValue = 4

        member this.SomeMethod1() =
            printfn "%d" letValue

        member this.SomeMethod2() =
            printfn "%d" this.memberValue
```

and so this one:

```fsharp
namespace Test.MyNamespace

    type MyClass() = 

        let letValue = 3
        member this.memberValue = 4

        member this.SomeMethod1() =
            printfn "%d" letValue

        member this.SomeMethod2() =
            printfn "%d" this.memberValue
```

However, this one 

```fsharp
namespace Test.MyNamespace

//module MyModule =

    type MyType =
        | SomeInt of int
        | SomeString of string
        | None

    type MyClass() = 

        let letValue = 3
        member this.memberValue = 4

        member this.SomeMethod1() =
            printfn "%d" letValue

        member this.SomeMethod2() =
            printfn "%d" this.memberValue
```

fails to compile with error:

`Cannot find namespace Test.MyNamespace.MyClass`

The error message is a bit misleading, as the real problem is with `MyType`. When reaching it, [getRootDecls](https://github.com/fsprojects/Fable/blob/master/src/fable-fsharp/FSharp2Fable.fs#L705) is being called with `rootNs = "Test.MyNamespace.MyClass"` (while the correct should be `rootNs = "Test.MyNamespace"`).

When using a `module` (first example) the problem doesn't occurs. In this case `getRootDecls` is called with the correct namespace (`rootNs = "Test.MyNamespace.MyModule"`) when it reaches `MyType`.

**Comment by alfonsogarciacaro** [comment]
Silly mistake, I should have checked it better. Many thanks for the report!
