### ISSUE TITLE
Generate separated statements for easy debugging

### ISSUE THREAD

**Issue by lijunle** [fsprojects/Fable#108]
### Description

Currently, the function body is concatenated as one big single statement. It is very hard to debug in browser,

For example, the following FSharp code:

```fs
let parse s =
    let input = Input.init s
    let result = Parser.run integer input
    match result with
    | Failure e -> Failure e
    | Success (v, next) -> Success v
```

Compile to (formatted by hand):

```js
var parse = exports.parse = function (s) {
  var input, result, v, next, e;
  return input = (0, _Input.init)(s),
    result = (0, _Parser.run)(integer, input),
    result.Case === "Success"
      ? (
        v = result.Fields[0][0],
        next = result.Fields[0][1],
        new _DomainTypes.Result("Success", v))
      : (
        e = result.Fields[0],
        new _DomainTypes.Result("Failure", e));
};
```

This could be much better:

```js
var parse = exports.parse = function (s) {
  var input = (0, _Input.init)(s);
  var result = (0, _Parser.run)(integer, input);
  return result.Case === "Success"
    ? (function () {
      var v = result.Fields[0][0];
      var next = result.Fields[0][1]
      return new _DomainTypes.Result("Success", v))()
    : (function () {
      var e = result.Fields[0];
      return new _DomainTypes.Result("Failure", e))();
};
```

Then, we can set breakpoint on each `var` statement to see what is returning.

**Comment by alfonsogarciacaro** [comment]
Yeah, this was one of the [caveats](https://github.com/fsprojects/Fable/blob/master/README.md) as this is the way [do expressions](http://wiki.ecmascript.org/doku.php?id=strawman:do_expressions) compile in Babel. Using do expressions makes the compilation much simpler and also the generated code is more compact and (hopefully) more performant. The problem, as you noted, is debugging is not ideal.

We could consider generating debug (with separated statements) and production code. Unfortunately, we're a small team and we have to focus on other priorities at the moment :( But definitely this will be something to look at in the future.

**Comment by alfonsogarciacaro** [comment]
As it happened other times, finally I yielded to reason and removed _do expressions_ 😉  The debugging experience should be much better now. You can check it with the new alpha version: `fable-compiler@next` and `fable-core@next`. Your sample above now compiles as follows:

```js
var parse = exports.parse = function (s) {
  var input = Input.init(s);
  var result = Parser.run(integer, input);

  if (result.Case === "Success") {
    var v = result.Fields[0];
    var next = result.Fields[1];
    return new _DomainTypes.Result("Success", v);
  } else {
    var e = result.Fields[0];
    return new _DomainTypes.Result("Failure", e);
  }
};
```

Please feel free to reopen the issue if you're not still happy with the results :+1:
