### ISSUE TITLE
Inline external project methods not inlining

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fable#112]
I have 2 project, one which contains my application and one which contains common code.
I’m having problems with the following code (which is in the application project):
```
let inline publishMessage settings (message: 'a) = 
    let queueName = typeof<'a>.FullName
    let username = settings.UserName
    ignore()
 
[<EntryPoint>]
let main argv =
 
    let settings = 
        { UserName = "guest"
          Password = "guest"
          HostName = "localhost"
          ExchangeName = "Test1" }
 
    publishMessage settings { Body = "Hello" } 
    RabbitQueue.publishMessage settings { Body = "Hello" } 
```
```RabbitQueue.publishMessage``` is the same as publishMessage but in the common project

It seems that RabbitQueue.publishMessage isn’t inlining like publishMessage is:

```
var settings, queueName, username;
return settings = new _RabbitQueue.QueueSettings("guest", "guest", "localhost", "Test1"),
(queueName = "RabbitQueue.Message1", username = settings.UserName, null),
(0, _RabbitQueue.publishMessage)(settings, new _RabbitQueue.Message1("Hello")),
0;
```

**Comment by alfonsogarciacaro** [comment]
True, I didn't foresee this problem :( It could be possible to inline external methods too but then we have to parse the whole external project and in some cases this may really slow down the compilation.

The easiest solution would be to compile the public inline functions like normal methods so they can be called as usual from external projects (when called internally they will still be inlined). Would this solution be acceptable to you?

**Comment by davidtme** [comment]
I'm not 100% sure what you mean - if I removed the inline I get the following from fable:
```
Cannot reference unknown type. If this a generic argument, try to make function inline
```

**Comment by alfonsogarciacaro** [comment]
Ok, so you're referencing a generic type in `RabbitQueue.publishMessage`. This is gonna be tricky :) Would it be possible to post the code of `RabbitQueue.publishMessage` here? Or do you have a link for your project?

**Comment by davidtme** [comment]
Sure, it's very rough - [RabbitQueue.fs.txt](https://github.com/fsprojects/Fable/files/240875/RabbitQueue.fs.txt)

**Comment by alfonsogarciacaro** [comment]
Yeah, this is complicated. As generic information is lost in runtime, the only way to do something like `typeof<'a>.FullName` is inlining the function in compile time, but unfortunately (right now) this is not possible across projects :( Is this a stopper for you? Can you refactor the code (for example, sending the type name as a string to `RabbitQueue.publishMessage`)?

**Comment by alfonsogarciacaro** [comment]
Unfortunately this is going to be difficult to fix. I tried to apply the "easy" solution explained above, but then trying to use `typeof<'T>` with generics would fail even for internal inline functions. So right now I just improved the error message (it will warn you if you're trying to access an inline function of an external project).

If you can think of another way to fix the problem please feel free to reopen the issue.

**Comment by davidtme** [comment]
How are the inline functions in F# Core handled i.e. in [prim-types.fs](https://github.com/fsharp/fsharp/blob/37a100b7caafde0f4df5a1924c9f65f4a18277a8/src/fsharp/FSharp.Core/prim-types.fs)?

**Comment by alfonsogarciacaro** [comment]
Inlining in the F# compiler has two functions: statically resolved generic parameters and performance, however it seems [it's not recommended to use `inline` only for performance](https://msdn.microsoft.com/en-us/library/dd548047.aspx). The AST provided by the compiler and used by Fable doesn't inline functions alone, Fable has to do it on its own.

**Comment by dsyme** [comment]
@alfonsogarciacaro Using inline for performance is ok.  It's just that some people tend to over-use it, splattering it everywhere.

We could in theory provide some apparatus to help with separate compilation and "inline".  I suppose the idea would be to give a way to get and save the table of "inline" expressions at the end of a compilation (basically the optdata resource), and then give a way to resurrect and specialize those.  But it's quite a big big job, so dealing with it in Fable makes sense for now.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the explanation, @dsyme! I don't think we need the F# AST to inline functions at the moment, my main purpose when adding this feature, rather than performance, was to be able to resolve generic types at compile time (as in runtime they're erased) and allow things like `typeof<`T>` in some scenarios like [the React Helper](https://github.com/fsprojects/Fable/blob/master/samples/browser/react/src/client/Fable.ReactHelper.fs#L309). But in cases like the one @davidtme revealed with cross projects references it gets complicated.

I'll also take the chance to confirm one thing: my understanding is that the AST provided by the compiler is always as is, and is not modified by passing options like `--optimize[+|-]`. Is that correct? 

There are still many parts of the F# compiler I don't know well and that's why I really appreciate the F# Technology Creator Workshop you and Tomas are organising. I'm really sure it will help a lot make Fable better!

**Comment by dsyme** [comment]
> I'll also take the chance to confirm one thing: my understanding is that the AST provided by 
> the compiler is always as is, and is not modified by passing options like --optimize[+|-]. Is that 
> correct? 

That's correct.  (Though if we provided the "inline" expressions then I believe that as things currently stand they _would_ be optimized.)
