### ISSUE TITLE
--symbols and referenced project

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fable#113]
Would it be posable to pass any specified symbols onto referenced projects?

I’m planning on having #if FABLE blocks in my common project. I can compile this project to javascript/.net no problems (using --symbols). When I try to compile the child project to javascript it blows up because FABLE isn’t defined - It tries to use json.net which is swapped out for json.stringify.

I've tried to create a Fable build configuration with FABLE symbol defined but is there anyway of using this from the fable compiler?

**Comment by alfonsogarciacaro** [comment]
After adding the `--refs` option I was considering to allow multiple project compilation but this proved to be quite complex as I didn't have it in mind at the beginning :/

What I did change is that now you can put `fableconfig.json` in any directory (before it had to be in the same directory where `fable` was run). So if you want to compile multiple projects at once my advice is to put a `fableconfig.json` file in the folder of each project and then create a batch or bash script like:
```
fable path/to/project1/
fable path/to/project2/
```

Is it possible to see the project you're working on? Or can you post the steps you take to do the compilation? I'd like to understand better why can't you easily define FABLE symbol in the child project. Also, when you talk about the common project is this a project reference (like [this](`RabbitQueue.publishMessage`)) or a [shared project](https://developer.xamarin.com/guides/cross-platform/application_fundamentals/shared_projects/)?

**Comment by davidtme** [comment]
I've posted up a demo project to https://github.com/davidtme/FableTest

**Comment by alfonsogarciacaro** [comment]
Thanks for that! Now I understand the problem better :)
