### ISSUE TITLE
ts2fable generates incorrect import directives

### ISSUE THREAD

**Issue by bilkusg** [fsprojects/Fable#119]
### Description

If I run ts2fable on an input file with exports the 

    [<Import()>] 

statement has only one string, but Import now requires two

### Repro steps

* Pick a valid .ts.d file ( I used the one from moment.js in npm )
* Run ts2fable on this file

### Expected behavior
Generated code should be valid for use within a project with statement like

        type [<Import("*","moment")>] Globals =

### Actual behavior

    type [<Import("moment")>] Globals =

### Known workarounds

Edit the statements in the generated code to add the missing value.

### Related information 

* Operating system Windows 10
* .NET Runtime, CoreCLR or Mono Version 4.6

**Comment by alfonsogarciacaro** [comment]
Actually this was already fixed but I forgot to update the npm package, sorry! I've published a new version numbered 0.1.14, can you please try that?

In any case the TypeScript parser needs (almost) a full rewrite using the TS type checker. I'm waiting until TS 2.0 is released as the compiler services are expected to change quite a bit. In the meantime, if you want to parse a definition file please tell me and I can give you a hand if necessary. We can also add it to the repo and npm for other users as well.

**Comment by bilkusg** [comment]
Tried 0.1.14 and confirmed fixed. Thanks
