### ISSUE TITLE
Array.map won't map from array of int to array of another type

### ISSUE THREAD

**Issue by funlambda** [fsprojects/Fable#120]
I'm having problems mapping from integer arrays to arrays of any other type:

```fsharp
type T = { Num: int; Str: string }

let a = [| 1; 2; 3 |]

let b = a |> Array.map (fun x -> x + 1)
printfn "%A" b // [ 2, 3, 4 ] as expected

let c = a |> Array.map string
printfn "%A" c // expected: [ "1", "2", "3"] actual: [ 1, 2, 3 ]

let d = a |> Array.map (fun i -> { Num = i; Str = "x"})
printfn "%A" d // expected: [ { Num: 1, Str: "x" }, { Num: 2, Str: "x" }, { Num: 3, Str: "x" }] actual: [ 0, 0, 0 ]

```

Looks like `a` is getting created as a new `Int32Array` (as opposed to a plain JS array), and the map function on `Int32Array` is always coercing values back to an int-valued number.

**Comment by alfonsogarciacaro** [comment]
Nice catch! Thanks a lot for the report and the detailed examples. You're absolutely right that the native `map` for Typed Arrays coerce values to the same time, so now Fable will use `Seq.map` instead when the input and output types don't match :+1:

While doing that I also noticed that mapping to typed arrays (from a non-typed arrays) wasn't working properly either. This is also fixed :)

It was expected that using typed arrays to compile numeric arrays would cause unexpected behaviour in some corner cases, but I think the performance boost was worth it. Hopefully, thanks to you fewer or even none of these corner cases remain!

**Comment by funlambda** [comment]
Thanks for the amazingly fast response! Also wanted to say thanks for all your hard work on Fable. I think it's an unbelievable project, and it looks like it could be a major leap forward for client-side development. Just started using it on a project and really love it so far! 👍 👍

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the kind words! I'm glad you like the project, but nothing would be possible without the community and that's why I really appreciate your feedback :) I'm also open to suggestions (always with a proper balance of added benefits/complexity) so just get in touch if you have any. Also, if you can contribute with examples, tutorials that'll be fantastic!
