### ISSUE TITLE
Forum or wiki?

### ISSUE THREAD

**Issue by bilkusg** [fsprojects/Fable#123]
I've been very impressed so far with what I've seen of Fable and its viability from a technical point of view. But unlike other projects, there doesn't appear to be any forum or wiki for users to post their experiences / silly questions / discussion items. So raising an issue here seems to be the only way to interact, and while I've been impressed with the responsiveness to my issues, I don't think it's the right place for everything.

Have I missed something?

**Comment by alfonsogarciacaro** [comment]
That's a very nice idea. Only my problem is that I'm not very good at keeping an eye to notifications from many different sites, so I'm trying to focus on Github and Twitter at the moment. Opening a forum would be great but it'd have to be mostly community-maintained. I'm fine with using Github issues for comments and suggestions, as it makes it easier to look up for them later. Also, right now the compiler is shaping up with community's feedback before releasing v1.0.0 so any comment is valuable and can open a discussion for new features :)

**Comment by Krzysztof-Cieslak** [comment]
Maybe just Gitter? It's working pretty well for most F# projects.

**Comment by alfonsogarciacaro** [comment]
Yeah, that should work (again I cannot promise I'll be checking it constantly). Probably the best timing to create the channel will be when the logo and the web are ready. Then we can also open a Twitter account :+1:

**Comment by alfonsogarciacaro** [comment]
Reopening as a reminder to create the Gitter channel when the logo is ready.

**Comment by alfonsogarciacaro** [comment]
Merge with #183
