### ISSUE TITLE
Online REPL

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsprojects/Fable#13]
It would be great to have an online REPL to show the capabilities of the compiler. Maybe @tpetricek can help here?

**Comment by alfonsogarciacaro** [comment]
Repl is already online

**Comment by tpetricek** [comment]
I put together a minimal reusable editor with autocomplete based on Suave that you could adapt if you wanted to have F# editor with more features :). It is still work in progress, but the first sketch is here: https://github.com/tpetricek/fsharp-web-editors-demo

(It has a Paket dependency on https://github.com/tpetricek/fsharp-web-editors, which contains code of the server & client side components, but the demo just references those - the idea is they should be very reusable and easy to embed.)

**Comment by alfonsogarciacaro** [comment]
Great, thanks for that! I'll reopen the issue so I remember to work on this again :)

**Comment by alfonsogarciacaro** [comment]
Closing this for now, it will be revisited later.
