### ISSUE TITLE
Module binding shadows top-level binding

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/Fable#130]
### Description

```
let a = 10

module B = 
  let c = a 
  let a = 13

printfn "Hello: %d" B.c
```

### Repro steps

1. `build/fable test.fsx`
2. `node test.js`

### Expected behavior

Should print `Hello: 10`

### Actual behavior

Prints `Hello: undefined`

**Comment by tpetricek** [comment]
This is caused by the way `let a = 13` is compiled - it declares a new local variable `a` that shadows the one available in the outer scope.

**Comment by alfonsogarciacaro** [comment]
Blame JavaScript hoisting! ;)

This was a bit challenging but I think I managed to tackled it and fixed some other issues along the way. Now the private variables generated from the module members have different names than the members themselves to prevent collisions.

The code is getting a bit more complicated but hopefully we're getting closer to a more bullet-proof system. I'll be uploading shortly a new version with this and (hopefully) other fixes.

Thanks a lot for spotting the issue!
