### ISSUE TITLE
fix links in header bar

### ISSUE THREAD

**Issue by forki** [fsprojects/Fable#136]
![image](https://cloud.githubusercontent.com/assets/57396/15353289/9ee47506-1ce8-11e6-9780-4748a38e3f51.png)

I tried to fix, but didn't find where this comes from.

**Comment by tpetricek** [comment]
I'll run `./build.sh PublishDocs` - I think the current page is just merged version of my PR, but to get all links right, we need to regenerate the docs.

It comes from here: https://github.com/fsprojects/Fable/blob/master/docs/docs.fsx#L32

**Comment by tpetricek** [comment]
Fix is live now :) Thanks!
