### ISSUE TITLE
Type abbreviations in namespaces fail to compile

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fable#140]
### Description

Fable fails to compile a type abbreviation in a namespace

### Repro steps

Put this code in ``test.fsx`` and compile it using Fable.exe

```fsharp
namespace Test

open System

type IAsyncEnumerator<'T> =
    abstract MoveNext : unit -> Async<'T option>
    inherit IDisposable

type IAsyncEnumerable<'T> = 
    abstract GetEnumerator : unit -> IAsyncEnumerator<'T>

type AsyncSeq<'T> = IAsyncEnumerable<'T>
```

### Expected behavior

Expect: successful compilation

### Actual behavior

```json
{"type":"Error","message":"the type 'AsyncSeq`1' does not have a qualified name"
}
```

### Known workarounds

Put the code in a module

**Comment by tpetricek** [comment]
This is the error we've been getting with JSON type provider too!

**Comment by alfonsogarciacaro** [comment]
This should be fixed now, thanks a lot for the report, Don! And yes, this seems to be related to the error with the JSON type provider, it's a very helpful info to start implementing it :+1:
