### ISSUE TITLE
Project file cracking should accept MSBuild properties

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fable#141]
### Description

Problem: When using a ``.fsproj`` file, there is not current way to pass properties like ``Configuration`` = ``Debug``

### Details

Fable calls ``GetProjectOptionsFromProjectFile``.  This accepts an optional ``properties`` parameter, corresponding to MSBuild arguments like ``/p:Configuration=Release``.  

Fable should probably accept a ``--projectproperty:Configuration=Release`` argument to pass through to GetProjectOptionsFromProjectFile, to help interpret the project file under the right settings.

### Workaround

Use a project file that doesn't need any configuration :)

### Severity

This is not blocking, I was just fiddling around trying to compile some existing F# projects.

**Comment by alfonsogarciacaro** [comment]
Implement in v0.3.1 :) Thanks a lot for the tip!
