### ISSUE TITLE
Docs say "--projFile" is default argument, but it needs to be explicit

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fable#142]
### Description

The [docs](http://fsprojects.github.io/Fable/docs/compiling.html) say you can just do ``fable foo.fsproj`` instead of ``fable --projFile foo.fsproj``.  But when I try that I get

```fsharp
Unhandled Exception: System.InvalidOperationException: The input list was empty.

   at Microsoft.FSharp.Collections.FSharpList`1.get_Head()
   at Fable.Main.readOpts@15(FSharpMap`2 opts, FSharpList`1 _arg1) in C:\GitHub\
dsyme\Fable\src\fable-fsharp\Main.fs:line 18
   at Fable.Main.readOptions(String[] argv) in C:\GitHub\dsyme\Fable\src\fable-f
sharp\Main.fs:line 26
   at Fable.Main.main(String[] argv) in C:\GitHub\dsyme\Fable\src\fable-fsharp\M
ain.fs:line 148
```

**Comment by alfonsogarciacaro** [comment]
Ah, ok, you're using directly `Fable.exe`. The docs only cover when you call the [node bootstrapper](https://github.com/fsprojects/Fable/blob/master/src/fable-js/index.js) instead, as this normalises the arguments before sending them to the .NET/Mono process. There're also some arguments that don't apply to `Fable.exe`, neither will it read directly `fableconfig.json` by itself.

If you've built the project yourself, to run the node bootstrapper, you'd have to do something like (from the project root folder):

```
node build/fable path/to/foo.fsproj
```

> Note: This is equivalent to `node build/fable/index.js`. Node will load `index.js` by the default when you pass a directory.

If you don't have node installed you can just download the binary from nodejs.com.

I hope this helps, please tell me if you've any other question and thanks a lot for checking the tool!
