### ISSUE TITLE
Running fable with -w gives file is being used exception

### ISSUE THREAD

**Issue by ritcoder** [fsprojects/Fable#144]
### Description

Running `fable -w` run the first time. Subsequent times fail with `file in use by another process` exception

### Repro steps

Run `fable -w`

### Expected behavior

Files are compiled and webpack-dev-server runs

### Actual behavior

````
u:\Work\PlayGround\Fable\CreatingVSCodePlugin\test2>fable -w
Start compilation...
Compiled Fable.Helpers.React.fs at 7:36:31 PM
Compiled models.fs at 7:36:31 PM
Compiled reactTest.fsx at 7:36:31 PM
Compiled main.fsx at 7:36:31 PM
Watching u:\Work\PlayGround\Fable\CreatingVSCodePlugin\test2\src
Cannot read project options: The process cannot access the file 'u:\Work\PlayGround\Fable\CreatingVSCodePlugin\test2\src\main.fsx' because it is being used by another process.
Compiled main.fsx at 7:38:01 PM
Cannot read project options: The process cannot access the file 'u:\Work\PlayGround\Fable\CreatingVSCodePlugin\test2\src\main.fsx' because it is being used by another process.
Cannot read project options: The process cannot access the file 'u:\Work\PlayGround\Fable\CreatingVSCodePlugin\test2\src\main.fsx' because it is being used by another process.
````

### Known workarounds

Run `fable` manually when there is a change

### Related information 

* Operating system: Window 10
* Branch: Fable 0.2.14
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by alfonsogarciacaro** [comment]
Thanks for the report. Can you please post the `fableconfig.json` you're using? Also, if you have the copy in Github or somewhere public a link would be very helpful to reproduce the issue. Cheers!

**Comment by ritcoder** [comment]
Hi,
I'm migrating an application from `elm` to `f#` so cannot post it online. One observation is that it affects only the `projFile`. When I edit any other file, it compiles just fine. It is only the `main.fsx` file that gives that error.


`fableconfig.json` below

````
{ "module": "commonjs",
  "sourceMaps": true,
  "projFile": "./src/main.fsx",
  "outDir": "build",
  "scripts":{
  },
  "targets":{
    "watch":{
      "scripts":{
        "postbuild": "webpack-dev-server --content-base public/"
      }
    }
  }
}
````

**Comment by alfonsogarciacaro** [comment]
This is very helpful, thank you! Yes, I didn't test the `--watch` option when modifying the the `.fsproj` file (or the main `.fsx` file in your case) so probably I didn't get it quite right. I'll fix that. For the moment, you can try using an empty `main.fsx` that's only loading the other files so you don't need to change it that much. Sorry for the inconvenience!

**Comment by ritcoder** [comment]
No problem. `main.fsx` is indeed loading other components and at such rarely modified.

**Comment by alfonsogarciacaro** [comment]
I've tried to reproduce the error by creating a test script:

```fsharp
// Test1.fsx
printfn "Hello from Test1"

// Test2.fsx
printfn "Hello from Test2"

// Test.fsx
#load "Test1.fsx"
#load "Test2.fsx"
```

Then I run: `fable Test.fsx -w` but I could modify without problems any file (including the "main" script, Test.fsx) both in Mac and Windows :/

If you can isolate a minimal project where the problem can be reproduced it will be really helpful to find out the cause. You can also try running the `--watch` option without the webpack server to check if this is what's blocking the file.

Cheers!

**Comment by ritcoder** [comment]
Actually, I was running `fable -w`  without `webpack`. I thought that was the case. Will look at a minimal project. Also, `watch` does not seem to be working with `fable -w` on the new `.fsproj` version. Always have to use just `fable`

**Comment by alfonsogarciacaro** [comment]
@irium's fix has been applied to v0.3.15. @ritcoder, can you please check if this fixed the issue for you? Thanks in advance!

**Comment by ritcoder** [comment]
Worked fine with the `fsproj`. Thanks.

**Comment by ritcoder** [comment]
Slight problem. When the code is recompiled, can it recompile all files that depend on it as well?

I had what I thought was a bug. It turned out not to be. I updated a file (`SemanticUi.fs`) and got an error in `TopPanel.fs` (`blah blah is not a function`). Code worked after editing and saving `TopPanel.fs` (just added a space and it recompiled). The error was because that file had to be recompiled since I had changed the structure of the previous file.

Compile on save is working fine so identifying dependents and recompiling them could be a good addition.

**Comment by alfonsogarciacaro** [comment]
Hmmm, this is going to be complicated because the F# compiler doesn't give you a file dependency graph (or at least I haven't seen it), so I'd have to go through all the files to check if there are references to the modified one and then probably watch compilation won't be that fast anymore.

I'll have a look. At least you have file order in F# so you only have to look at the files coming *after* the modified one.

**Comment by 7sharp9** [comment]
There's an event that's fired that lets you know to re-check dependants.

**Comment by ritcoder** [comment]
In the output js files, there are require statements that points to project files. I'm not sure how they are determined during compilation but can't that idea be used to build some kind of dependency graph during the first compilation? If it is possible, then watch compilation will lookup the graph to determine the dependents and recompile them - updating the graph in the process.

**Comment by alfonsogarciacaro** [comment]
Good one! Actually I was thinking of something similar after writing the comment, it should be possible to create a simple dependency graph after the first compilation. I'll work on that.

@7sharp9, do you happen to know the name of the event? Is it one of the events raised by the `FSharpChecker` type?

**Comment by 7sharp9** [comment]
Yeah that's right, I'll let you know when I'm next using my computer, currently on phone.

**Comment by ritcoder** [comment]
Had an experience where one of my files had an error and hence first compilation failed. When the file was fixed, got some weird error: `Fable.Helpers.React.div is inlined but is not reachable. If it belongs to an external project try removing inline modifier`. Everything worked fine after killing the process and executing `fable -w` again got everything back to normal. I did try but could not replicate it.

Do you suppose that in the event where a complete compilation of the project has not been successful, all subsequent changes will trigger a full compilation until it is successful after which only the modified files are compiled?

**Comment by alfonsogarciacaro** [comment]
Inline expressions are giving me headaches, maybe I shouldn't have added that feature ;)

Inline expressions are stored in [a static collection](https://github.com/fsprojects/Fable/blob/master/src/fable-fsharp/FSharp2Fable.fs#L788-L790) and are never removed. I wonder how `Fable.Helpers.React.div` got "lost". If you encounter the error again and have any other clue, please write again.

In any case, your idea of forcing a full compilation when there're errors is a good one. I'll try to implement it :)
