### ISSUE TITLE
async best practice with fable calling 'traditional callback' apis

### ISSUE THREAD

**Issue by bilkusg** [fsprojects/Fable#146]
In playing around with mysql bindings, everything works as expected using the standard callback approach. And although I haven't yet tried it, I'm sure I could easily move to a promise-based approach, just using javascript promises from fsharp.

But I cannot see how to wrap a javascript function which expects a callback into something suitable for use within an async workflow.
I tried using Async.FromContinuations, which seems to exist in the Fable core, but it doesn't work properly unless you can call it with Async.StartWithContinuations, which doesn't exist in the Fable core.

What's the best approach here?.

**Comment by alfonsogarciacaro** [comment]
My idea was to implement an `AwaitPromise` extension for `Async` and interact with them the same way we do with `Task` in .NET, awaiting them when necessary in the `async` computation expression. I haven't done it, but I'll try to add the extension shortly to `Fable.Core`.

Thanks also for pointing out that `Async.StartWithContinuations` is missing! I'll implement it right away. For now, something like the following should work:

```fsharp
async { return Async.FromContinuations(myCont) } |> Async.StartImmediate
```

**Comment by tpetricek** [comment]
`AwaitPromise` sounds good to me!

In Ionide, I already added `StartAsPromise` (see [here](https://github.com/ionide/ionide-fsharp/blob/develop/src/Core/Control.fs#L57)), which would be good to have too.

**Comment by bilkusg** [comment]
I can't see how to use Async.FromContinuations with Async.StartImmediate. It either won't compile ( the suggestion made  above says that the async is returning an Async<Async<int>> instead of Async<unit>, or gives me an error when I try and call the return function ( which is undefined )

Maybe I'm just being silly and missing something which should be obvious. But what I wrote originally was:
````fsharp
let asyncget = 
      let wrapper (r,e,x) = // This should be my continuation function
          let connection = mysql.Globals.createConnection(connectionConfig)
          connection.connect()
          let processIt123 err result =  // this is a callback function
             Console.WriteLine (sprintf "Getting data err %A r %A" err r ) // this line reports that r is undefined
             r result // so this line fails as r is not a function
          let seatQuery = connection.query.Invoke("select * from mytable",Func<IError,obj,unit> processIt123)
          ()
      async {
        return! Async.FromContinuations  wrapper
      }

let erh req res _ =  
    Async.StartWithContinuations(asyncget,(fun r->res?json $ r |> ignore),(fun e->()),(fun c->())) // what I wanted to do
    Async.StartImmediate asyncget // means that the callback function is undefined
    box ()

app.get(U2.Case1 "/api/sql/", erh) |> ignore
````

If I replace the call to FromContinuations with something which does a StartImmediate, I have nowhere to actually call the express result function, and if I try it anyway, it crashes at runtime saying that r is not a function ( which it isn't because it's undefined as I can see from the trace statement above.

And yes, I know this is unnecessary approach in this case, cos I can just call the express result function directly in my callback function, but the purpose is not to get something which just works, it's to define a clean and reusable pattern which I can leverage in more complex situations.

**Comment by alfonsogarciacaro** [comment]
Sorry, the code I wrote above was indeed mistaken 😅 I've been fixing several issues in the `Async` module but to prevent confusion, I'm closing this issue and continue on thread #151 which looks merrier 😸 Cheers!
