### ISSUE TITLE
Unsupported format of the sourcemap error when trying to debug from visual studio.

### ISSUE THREAD

**Issue by ReverseBlade** [fsprojects/Fable#147]
### Description
I would like to debug the code from visual studio however when ever I attach the debugger to it, VS gives me Unsupported format of the sourcemap error . I am not sure if this is VS fault or fable's

### Repro steps

Please provide the steps required to reproduce the problem

1. Run a sample from Edge.

2. Attach the debugger to correct edge instance.

* Windows 10
* VS 2015 .net 4.6.1
* Performance information, links to performance testing scripts

**Comment by alfonsogarciacaro** [comment]
I'm not using Visual Studio at the moment. In Visual Studio Code source maps work fine, but it's true they didn't a couple of versions (of VS Code) ago. The source maps are actually generated by Babel. I don't know what's exactly the source map format VS supports, but I'll try to investigate. If you can also find some information about this and post it, it'd be really helpful :)

**Comment by ReverseBlade** [comment]
This issue is not relevant with Visual Studio Code. Although we can think support for VS debugging is not so big deal actually it is. The reason is you can develop Html based UWP app with Visual Studio. Fable can also be useful there. Unfortunately the only way to debug such apps is to use Visual Studio or use something like Vorlon.JS. 

I also made a google search. Most relevant links were
https://connect.microsoft.com/VisualStudio/feedback/details/1873069/unsupported-format-of-the-sourcemap-errors
http://stackoverflow.com/questions/32445692/debugging-bundled-javascript-in-visual-studio-2015/32952254#32952254

Though these work arounds did not work. This is where  I got stuck.

**Comment by alfonsogarciacaro** [comment]
That's really helpful, thanks! So it's correct to assume you are using Webpack to bundle your files? I ask this to know if the issue comes from the way Babel or Webpack generates the source maps. If you're indeed using Webpack, have you tried any of the solutions proposed in [this thread](https://github.com/webpack/webpack/issues/1502#issuecomment-147627128)? (Like [this Webpack plugin](https://github.com/joevbruno/vs-fix-sourcemaps).)

Cheers!

**Comment by ReverseBlade** [comment]
Unfortunately, no. I was just trying your own samples out of box. I build them with fable and tried to debug them via VS. That was all.

**Comment by alfonsogarciacaro** [comment]
Perfect, thanks for the confirmation. I'll try to debug the examples on a machine with Visual Studio then to see if I can find out the problem.

**Comment by alfonsogarciacaro** [comment]
I've tried with Visual Studio Community 2015 Update 3 and it was able to read the source maps (albeit with imperfections). I'm closing the issue for now, please feel free to reopen if you still encounter problems. Thanks.

**Comment by ReverseBlade** [comment]
Yes I confirm that it works! Thank you for following this up. You are the best :) 👍 👍
