### ISSUE TITLE
Support F# Events module

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/Fable#149]
### Description

`Microsoft.FSharp.Control.Event` module is really cool. Unfortunately Fabel doesn't support it at the moment - any usage of functions from this module results in compilation error (for example `Cannot find replacement for Microsoft.FSharp.Control.Event.publish`

### Repro steps

1. Use any function from `Microsoft.FSharp.Control.Event`

### Expected behavior

Magic :tada: 

### Actual behavior

Cannot find replacement for `Microsoft.FSharp.Control.Event.___`

### Known workarounds

Don't use Event module :disappointed:

**Comment by tpetricek** [comment]
I think better workaround is to use the `Observable` module - is there anything in `Event` that's missing in `Observable`? (For mixing with `async` and in a few other ways, observable is actually a better choice...)

**Comment by alfonsogarciacaro** [comment]
Yes, I thought the same too, that's why I implemented `Observable` and not `Event`. However, 	Krzysztof needs the events and he's implementing them himself, so I've absolutely no intention of stopping him ;)

**Comment by Krzysztof-Cieslak** [comment]
Yes, I probably could use `Observable` instead. But, well, I don't see any disadvantage in adding more compatibility :smile: - as Alfonso mentioned, I'm already working on it: https://github.com/fsprojects/Fable/pull/150. Code reviews welcomed and appreciated.

**Comment by tpetricek** [comment]
Yep, no reason not to have them!

**Comment by tpetricek** [comment]
If I'm correct, this is now closed by #150

**Comment by alfonsogarciacaro** [comment]
Yes, you are! I forgot to close it, sorry 😅
