### ISSUE TITLE
Fable output can sometime be too terse

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/Fable#153]
### Description

Sometimes the output of Fable indicates a successful build but no files apear to be written to disl.

### Repro steps

Please provide the steps required to reproduce the problem

1. Fable -m commonjs <outlocation> <projectfile>

### Expected behavior

Start compilation...
Compiled Observable.fs at 9:55:04 AM
Compiled fetch.fs at 9:55:04 AM
Compiled Apis.fs at 9:55:04 AM
Compiled Types.fs at 9:55:04 AM
Compiled Library1.fs at 9:55:04 AM

Files listed as compiled exist on disk

### Actual behavior

output folder is empty

### Known workarounds

Please provide a description of any known workarounds.

### Related information 

Osx
* Master
* .Mono 4.4.0

**Comment by 7sharp9** [comment]
It would be great if a `--diagnostic` switch could be added where more detailed information is added to the output such as full path output and timings of the various stages of fable.

**Comment by ritcoder** [comment]
Are you using a `fableconfig.json` file? Do share if so. Also, it is that it works one time and at other time it does not?

**Comment by 7sharp9** [comment]
No `fableconfig.json` generally I just seemed to loose the output, I since rebooted and did some other things and they get generated now.  I would like to have a --diag option to get more detailed stats about whats happening.  :-)

**Comment by ritcoder** [comment]
Oh ok. If it works one time and not the other then getting more details will help. Perhaps, it could include an additional parameter to indicate how detailed it should be.

**Comment by alfonsogarciacaro** [comment]
This makes a lot of sense. I think we can add a `--verbose` option an output more info for advanced users. This will be useful to add warnings in particular situations too.
