### ISSUE TITLE
Cannot read property 'indexOf' of undefined error when disposing object [Observable]

### ISSUE THREAD

**Issue by ritcoder** [fsprojects/Fable#158]
### Description

I wrote some small abstraction around `Observable` and dispose doesn't work. From the info from debugging, the `this` in `_fableCore.Array.removeInPlace(w, this.listeners)` is actually the `IDisposal`.

### Repro steps

Please provide the steps required to reproduce the problem

````
//eventTest.fsx
#r "node_modules/fable-core/Fable.Core.dll"

open System
open Fable.Core
    
module Signals =
  open System

  type SimpleObserver<'t>(f) =
    interface IObserver<'t> with
      member x.OnNext v = f v
      member x.OnError e = ()
      member x.OnCompleted () = ()

  type Inbox<'t>() =
    let listeners = ResizeArray<IObserver<'t>>()

    member x.Post v =
      for listener in listeners do listener.OnNext v

    interface IObservable<'t> with
      member x.Subscribe w =
        listeners.Add w
        { new IDisposable with
            member x.Dispose() = listeners.Remove w |> ignore }

  let init<'a> () =
    let inbox = Inbox<'a>()
    let subscribe callback = Observable.subscribe callback inbox
    inbox.Post,subscribe
````
````
//index.js
var a = require("./eventTest")

let fns = a.Signals.init()
let post = fns[0]
let sub = fns[1]

//subscribe
let dis = sub(function(x){ console.log(x); })
post(1)
post(2)
dis.dispose(); //error
````

````
//from command line
node index.js
````

### Expected behavior

No error :)

### Actual behavior

````
u:\Temp\t>node index.js
1
2
U:\Temp\t\node_modules\fable-core\fable-core.js:709
    var i = xs.indexOf(item);
              ^

TypeError: Cannot read property 'indexOf' of undefined
    at Object.FArray.removeInPlace (U:\Temp\t\node_modules\fable-core\fable-core.js:709:15)
    at Object.dispose (U:\Temp\t\eventTest.js:130:32)
    at Object.<anonymous> (U:\Temp\t\index.js:11:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
````

### Known workarounds

Don't dispose :(

After some digging, the offending code is
````
//what is generated. this in the dispose function is actually _ref
    {
        key: "subscribe",
        value: function subscribe(w) {
          var _ref;

          return this.listeners.push(w), 
            ( _ref = {}
            , _defineProperty(_ref, _fableCore.Symbol.interfaces, ["System.IDisposable"])
            , _defineProperty(_ref, "dispose", function () {
              _fableCore.Array.removeInPlace(w, this.listeners);
            }), _ref);
        }
      }

//what works
    {
        key: "subscribe",
        value: function subscribe(w) {
          var _ref, _that = this; //introduced that

          return this.listeners.push(w), 
            ( _ref = {}
            , _defineProperty(_ref, _fableCore.Symbol.interfaces, ["System.IDisposable"])
            , _defineProperty(_ref, "dispose", function () {
              _fableCore.Array.removeInPlace(w, _that.listeners);
            }/*.bind(this) also works */), _ref);
        }
      }
````

### Related information 

* Operating system Windows 10
* Branch 0.3.2
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by alfonsogarciacaro** [comment]
Nice catch! This is going to be tricky. Lambdas could be used to translate members in object expression so the enclosing `this` is captured. But then you can still make a reference the object expression itself... Hmm, I need to take a closer look into this.

**Comment by ritcoder** [comment]
I was able to workaround it by 'closing' the listeners and disposable together. In the generated output, the `this` is not used at all. Below are the two implementations I tried. 

Either

    type Inbox<'t>() =
      let listeners, createDisposable = 
        let listeners = ResizeArray<IObserver<'t>>()
        let createDisposable w = //very close to listeners so no this 
          { new IDisposable with
              member __.Dispose() = listeners.Remove w |> ignore }
        listeners, createDisposable    

      member x.Post v =
        for listener in listeners do listener.OnNext v

      interface IObservable<'t> with
        member x.Subscribe w =
          listeners.Add w
          createDisposable w 

or

    type Inbox<'t>() =
      let listeners, add = 
        let listeners = ResizeArray<IObserver<'t>>()
        let add w = //moved add and createDisposable here
          listeners.Add w
          { new IDisposable with
              member __.Dispose() = listeners.Remove w |> ignore }
        listeners, add    

      member x.Post v =
        for listener in listeners do listener.OnNext v

      interface IObservable<'t> with
        member x.Subscribe w = add w


Went with the second though in my port.

**Comment by alfonsogarciacaro** [comment]
Seems I managed to fix to it :) At the end it was not that difficult to capture the parent `this`. Now it's possible to reference both the enclosing type and other members of the object expression. The first code you posted is working now, it's even possible to use nested object expressions :+1:

I'll upload shortly a new version to npm with the fix.
