### ISSUE TITLE
When Type and Module have same name, the 2nd overrides the first

### ISSUE THREAD

**Issue by ritcoder** [fsprojects/Fable#166]
### Description

When a module and type are defined in the same file with the same name, the code compiles fine but does not work. The 2nd overrides the first.

### Repro steps
````
type Cmd<'a> =
  | None
  | Value of 'a

module Cmd =
  let toString = function
    | None -> "no value"
    | Value x -> "Some value"

let test = Cmd.None |> Cmd.toString
````

### Expected behavior

````
var Cmd = exports.Cmd = function Cmd() {
  _classCallCheck(this, Cmd);

  this.Case = arguments[0];
  this.Fields = [];

  for (var i = 1; i < arguments.length; i++) {
    this.Fields[i - 1] = arguments[i];
  }
};

var Cmd = exports.Cmd = function ($exports) {
  var toString = $exports.toString = function (_arg1) {
    var x;
    return _arg1.Case === "Value" ? (x = _arg1.Fields[0], "Some value") : "no value";
  };

  return $exports;
}(exports.Cmd);
````

````
u:\Temp\t>node index.js
no value
````

### Actual behavior

    //generated code
    var Cmd = exports.Cmd = function Cmd() {
      _classCallCheck(this, Cmd);

      this.Case = arguments[0];
      this.Fields = [];

      for (var i = 1; i < arguments.length; i++) {
        this.Fields[i - 1] = arguments[i];
      }
    };

    var Cmd = exports.Cmd = function ($exports) {
      var toString = $exports.toString = function (_arg1) {
        var x;
        return _arg1.Case === "Value" ? (x = _arg1.Fields[0], "Some value") : "no value";
      };

      return $exports;
    }({});

````
u:\Temp\t>node index.js
U:\Temp\t\typeWithModule.js:46
  var test = exports.test = Cmd.toString(new Cmd("None"));
                                         ^

TypeError: Cmd is not a constructor
    at U:\Temp\t\typeWithModule.js:46:42
    at Object.defineProperty.value (U:\Temp\t\typeWithModule.js:5:5)
    at Object.<anonymous> (U:\Temp\t\typeWithModule.js:13:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
````

### Known workarounds

Use different names

### Related information 

* Operating system
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by alfonsogarciacaro** [comment]
This is tricky. It could be possible to implement this with private members modifying the name of the variable, but that would still cause conflicts in public exports. For now, I just added a check and error message at compile time to prevent unexpected behaviour at runtime. I hope that's fine with you. Thanks for the report!

**Comment by ritcoder** [comment]
That is fine. I had already changed that in my code but thought it was right to report it so that it is either fixed or an error is thrown. It is much better that the code does not compile so there are some guarantees around the compiled code. Maybe it could be looked at in the future.
