### ISSUE TITLE
StringEnum error when in pattern match

### ISSUE THREAD

**Issue by ritcoder** [fsprojects/Fable#167]
### Description

When a `StringEnum` is used in pattern matching, it is treated as the same as a type without `StringEnum`

### Repro steps

```
#r "node_modules/fable-core/Fable.Core.dll"

open System
open Fable.Core
open System.Collections.Generic

[<StringEnum>]
type Field = OldPassword | NewPassword | ConfirmPassword

let test = function
  | OldPassword -> "op"
  | NewPassword -> "np"
  | ConfirmPassword -> "cp"

let check = test NewPassword
```

### Expected behavior

`np`

### Actual behavior

Got `op`

Code was translated as

    var test = exports.test = function (_arg1) {
      return _arg1.Case === "NewPassword" ? "np" : _arg1.Case === "ConfirmPassword" ? "cp" : "op";
    };

    var check = exports.check = test("newPassword");

### Known workarounds

Don't use `StringEnum` if there will be pattern matching

### Related information 

* Operating system
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by alfonsogarciacaro** [comment]
I think it's difficult to provide support for all operations  on union cases with special attributes, but you're right that pattern matching with StringEnum makes lot of sense. Implemented in 0.3.4, thanks!
