### ISSUE TITLE
Map class is overwritten

### ISSUE THREAD

**Issue by davidoptima** [fsprojects/Fable#168]
### Description

I’m working on a RPG game so I’ve come across a problem because I’m using a record with a property called Map.  A variable is being declared called Map which means the built in Map class is overwritten

### Repro steps

``` F#
module Main

type RenderMap = 
    { Points : Map<int * int, string>
      Width : int
      Height : int }

type RenderState = 
    { Now : int
      Players : Map<int, string>
      Map : RenderMap }

let gameState = 
    { Now = 1
      Map = 
          { Points = Map.empty
            Width = 1
            Height = 1 }
      Players = Map.empty }

[<EntryPoint>]
let main argv = 
    printf "%A" gameState
    0
```

### Expected behavior

```
{"Now":1,"Players":[],"Map":{"Points":[],"Width":1,"Height":1}}
```

### Actual behavior

```
ERROR: index.js:30
contents: (Now = 1, Map = new RenderMap(new Map(), 1, 1), new RenderState(Now, new Map(), Map))
TypeError: Map is not a function
```

### Known workarounds

Rename property 

### Related information 

* Windows 10
* Master

**Comment by alfonsogarciacaro** [comment]
Hmm, we're having name conflicts today ;) It should be possible to fix for it in nested modules but not in the root one as the export must be declared as a variable with the same name. I think we can solve the issue by adding `Map` (and other native JS classes) to the list of reserved words. This way Fable will throw an error when trying to use it in a root module but just change the internal name when used in a nested module. I'll give it a try :)
