### ISSUE TITLE
Add --watch option to CLI tool

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsprojects/Fable#17]
F# compiler services take some seconds to warm up, adding a watcher should increase the speed of continuous builds. Maybe @rneatherway can provide some insight on the most efficient way to load the code AST. The current method to do it is [here](https://github.com/fsprojects/Fable/blob/master/src/Main.fs#L20-L48).

**Comment by xavierzwirtz** [comment]
I know FAKE has a well tested [file watching system](https://github.com/fsharp/FAKE/blob/448a0e59aa1381714d045bf81c3ab5692aad6259/src/app/FakeLib/ChangeWatcher.fs#L52), I would suggest using that.

**Comment by xavierzwirtz** [comment]
We had a lot of issues with catching all changes on all OS versions.

**Comment by rneatherway** [comment]
I use a filesystemwatcher: https://github.com/fsharp/FsAutoComplete/blob/master/FsAutoComplete/Program.fs#L46. It's debounced to only register a change if it hasn't been triggered for at least a second.

**Comment by alfonsogarciacaro** [comment]
Good hints, thank you two!

**Comment by alfonsogarciacaro** [comment]
The option has been added, closing.
