### ISSUE TITLE
Add a comparison with similar projects

### ISSUE THREAD

**Issue by iongion** [fsprojects/Fable#170]
Basically this http://fsharp.org/use/html5, but with your own words and analysis.

**Comment by alfonsogarciacaro** [comment]
I have to think about this. I understand that would be useful for users trying to find the most appropriate tool for their use case, but I'm always reluctant to make comparisons with other projects too publicly, as each one should have the right to speak for themselves. A comparison of this type is usually better done by somebody more "impartial" ;)

**Comment by iongion** [comment]
Problem is that there are so many incarnations and people don't know what to use and why to use. For example, core library support list, F# language feature support, easyness of development, easyness of deployment(packaging,compilation,optimization)

**Comment by tpetricek** [comment]
I'd say it makes sense to wait for a few months with this - Fable is still fairly new and the situation will become simpler after a few months.

**Comment by joeblew99** [comment]
Are there / plans for bindings to standard javascript libs ?
For example react, flux ?

**Comment by alfonsogarciacaro** [comment]
Hi! Teresa are already buildings for browser ando node apis, and other popular js libraries, including React, check fable-import packages in npm (there's also a react example in the repo, I'll put it also in the Web soon). for other libs you can make bindings yourself, check ts2fable in npm and Interacting with JS  in the docs :)

**Comment by alfonsogarciacaro** [comment]
As Tomas said, it's a bit difficult to make a comparison at the moment because Fable is adding features very quickly. I also don't know well about other similar projects 😅 We'll try to add more samples and tutorials and improve the docs so it's easier for developers to make a decision.
