### ISSUE TITLE
Difference between Seq.map and Array.map

### ISSUE THREAD

**Issue by ritcoder** [fsprojects/Fable#171]
### Description

Test testing some paging code and got different output depending on which of `Seq.map` and `Array.map` I used. I suspect it may have something to do with the typedarray (yet to use one)

### Repro steps

Code file

    //listtest.fsx
    let data = [| 1 .. 10 |]
    let page size page data =
      data
      |> Array.skip ((page-1) * size)
      |> Array.take size
      // |> Array.ofSeq

    let test1 =
      [| 1..5 |]
      |> Array.map (fun x -> page 3 x data)
      // |> Array.ofSeq

    let test2 =
      [| 1..5 |]
      |> Seq.map (fun x -> page 3 x data)
      |> Array.ofSeq

    let test =
      [| "test1", test1
        "test2", test2 |]

Node

    var a = require("./listtest")
    console.log(JSON.stringify(a.test))

### Expected behavior

Similar results for both tests

### Actual behavior

    [ ["test1",{"0":0,"1":0,"2":0,"3":10,"4":0}]
    , ["test2",[ {"0":1,"1":2,"2":3}
               , {"0":4,"1":5,"2":6}
               , {"0":7,"1":8,"2":9}
               , {"0":10}
               , {} ]]]

Result of test one is not what was expected.

### Related information 

* Operating system
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by alfonsogarciacaro** [comment]
Argh, this is bug #120 coming back. That's funny, I just had a discussion with Don Syme yesterday (#169) and I assured him all the core lib methods were working fine both with typed and non-typed arrays, I've been proven wrong too quickly 😅 I'm afraid the solution will be to give up on [using the native `map` method](https://github.com/fsprojects/Fable/blob/master/src/fable-fsharp/Replacements/Replacements.fs#L955-L960) as it's a bit risky with typed arrays (they always coerce the output).

**Comment by alfonsogarciacaro** [comment]
The fix has been published in v0.3.6. I also noticed `skip` wasn't throwing an error when there were not enough elements, so I also updated `fable-core` to v0.1.2 to fix that. Please tell me if this still doesn't work for you. Cheers!
