### ISSUE TITLE
Array / List tryItem missing

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fable#178]
Error message when trying to use Array / List tryItem

Cannot find replacement for Microsoft.FSharp.Collections.Array.tryItem

**Comment by alfonsogarciacaro** [comment]
Thanks for the tip. I took most of the collection functions from FunScript which was based in F# 3 so it may be that some of the new collection functions in F# 4 are missing. I still need to make a thorough check to make sure everything is there but for now I took the chance to add a few other functions: `tryHead`, `tryLast`, `findBack`, `tryFindBack`, `findIndexBack`, `tryFindIndexBack` :+1:

Please update `fable-compiler` to v0.3.12 and `fable-core` to v0.1.5 to get the fix.
