### ISSUE TITLE
Recompile dependant files on watch compilation

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsprojects/Fable#182]
See [this comment](https://github.com/fsprojects/Fable/issues/144#issuecomment-223783866).

**Comment by alfonsogarciacaro** [comment]
Hi @ritcoder! Can you please give it a try to v0.3.17 and confirm if it works for you? This version should compile dependant files on watch compilation. Cheers!

**Comment by ritcoder** [comment]
Been using it for a while. only the updated files are recompiled for the most part. When compiling dependents, are they also listed in the console. If yes, then no dependent files were compiled. The only error I had was the one below. It worked after restarting.

````
Compiled NewCasePanel.fs at 8:39:16 PM
Compiled NewCasePanel.fs at 8:52:49 PM
Compiled Controllers.fs at 11:50:37 PM
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.extname (path.js:887:5)
    at FSWatcher.<anonymous> (C:\Users\Richard\AppData\Roaming\npm\node_modules\fable-compiler\index.js:216:24)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:12)
````

**Comment by alfonsogarciacaro** [comment]
Yes, dependent files should be also listed in the console. So it's not working for you? Are you using `fable-compiler@0.3.17`? It's working for me when I'm compiling the React sample in the repo (for example, if I modify `components.fs`, both `components.fs` and `client.fs` are recompiled). If you can upload your project of part of it it'd be very helpful to try to reproduce your problem on my machine. Are you on Windows, by the way. Seems Node's file watcher may work differently on Windows.

**Comment by ritcoder** [comment]
Interesting. It was still `0.3.14`. Did `npm install` instead of 'npm install -g'. Will do well to check versions on future reports. Updated to `0.3.17` and updating one file (`SemanticUi.Extras.React.fs`) causes some two dependents (`NewCasePanel.fs` and `CaseContactsPanel.fs`) to recompile so it is working fine. 

One thing though is when it identifies changes and is about to compile, can it display something (like `Start compilation...`)? Reason is that compilation mostly takes its sweet time to start and you are not sure of what it is doing until you see the message `compiled xyz at 0:00:00 PM`.

**Comment by alfonsogarciacaro** [comment]
I'm glad to hear it works 😄 About your suggestion, it's a good point and it's not difficult at all to implement. I was always testing the watch compilation with small projects so I didn't notice the issue because compilation was really fast. Thanks for the tip! 👍

**Comment by ritcoder** [comment]
After using it for a while, it mostly works well. It does give way after some pressure. When the following are combined, it appears to get confused.

- error in the files (especially multiple files)
- adding new files to the project
- reordering files
- Saving of multiple files (e.g. editing multiple files and using save all)

Can't really point how to reproduce it but when I notice strange errors from the app, running `fable` in another terminal should get thing back to normal. After that further edits are correctly taken care of by the one watching.
