### ISSUE TITLE
Where to find React.renderComponent

### ISSUE THREAD

**Issue by ritcoder** [fsprojects/Fable#185]
### Description

I'm trying to implement a `portal` in react as shown [here](https://github.com/ryanflorence/react-training/blob/gh-pages/lessons/05-wrapping-dom-libs.md#portals)

I can't seem to find the equivalence of `React.renderComponent`. Where can I find out?

**Comment by alfonsogarciacaro** [comment]
I cannot find this method in the [React type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts). Is it a new method or is it coming from an addon? If you're sure the method is there you can still [call it dynamically](http://fsprojects.github.io/Fable/docs/interacting.html#dynamic-programming).

**Comment by ritcoder** [comment]
Just checked and couldn't find it in the `react` import either. Let me find out if it is a new function or an obsolete one.

**Comment by ritcoder** [comment]
It is now  `ReactDOM.render`. Tried it and was getting some errors but at this point it is not a fable issue. Will look into what is wrong. Thanks.
