### ISSUE TITLE
Building an .fsproj doesn't play well with non-interface .fs files in node modules

### ISSUE THREAD

**Issue by psfblair** [fsprojects/Fable#188]
### Description

I have an .fsproj project which is dependent on ```fable-import-react```. Although interface declaration files are not compiled to .js, the ```Fable.Helpers.React.fs``` file is. So my build output directory winds up looking like this:

```
build/
   dist/
      app/  [my code here, including Components.js]
      node_modules/
           fable-import-react/  [Fable.Helpers.React.js here]
```

as a result of the build, the exports in the ```Components.js``` file require ``./../node_modules/fable-import-react/Fable.Helpers.React``.

However, when I run this through brunch to concatenate the files, the Fable.Helpers.React module gets fed to ```require.register``` as ``fable-import-react/Fable.Helpers.React`` and as a result I get a "Component not found" error.

There is a filter in brunch that allows regex matching/replacing on module path names, but apparently it doesn't run on anything that starts with ``node_modules``. I'm opening an issue with them on this.

However, it would seem to me that when a node module's fs file is compiled to js, it should go under the same root as the application code; i.e, shouldn't the folder structure be:

```
build/
   dist/
      app/  [my code here, including Components.fs]
      fable-import-react/  [Fable.Helpers.React.fs here]
```

### Repro steps

Steps to reproduce the problem:

* Create a project with a code dependency on ```Fable.Helpers.React```. Use .fsproj and follow the instructions in the fable-import-react README for .fsproj projects.
* The ``fableconfig.json`` file is as follows:
```
{
    "ecma": "es2015",
    "outDir": "build/dist",
    "scripts": {
        "prebuild": "npm install",
        "postbuild": "cp node_modules/fable-import-react/package.json build/dist/node_modules/fable-import-react"
    }
}
```
* Run fable on the project.
* Install brunch. The relevant node modules need to be added to ```package.json```. The minimal ``brunchconfig.js`` file looks like this:
```
exports.config = {

  paths: {
    watched: [
      'app/assets', 
      'build/dist' 
    ]
  },

  files: {
    javascripts: { joinTo: 'app.js' },
  },

  plugins: {
    babel: { presets: ['es2015', 'react'] }
  },
};
```
* Run ``brunch build``.

### Expected behavior

All modules will be found when loading the application in the browser.

### Actual behavior

```
Components.js:5Uncaught Error: Cannot find module 'build/dist/node_modules/fable-import-react/Fable.Helpers.React' from 'build/dist/app/Components.js'
```

### Known workarounds

A real hack: Copy the ``Fable.Helpers.React.fs`` file to a top-level directory before compiling.

This requires the ``fableconfig.json`` to look like this:

```
{
    "ecma": "es2015",
    "outDir": "build/dist",
    "scripts": {
        "prebuild": "cp node_modules/fable-import-react/Fable.Helpers.React.fs fable-import-react/"
    }
}
```
and the path to the file needs to be changed in .fsproj to point to ```fable-import-react/Fable.Helpers.React.fs```. (The file has to live permanently in the top-level directory, or the entry in the .fsproj file will disappear after msbuild runs.)

This is naturally extremely brittle, and it requires creating a separate source directory outside ```app/``` for every node module that contains non-interface .fs files.

### Related information 

* Operating system: OS X 10.11.5
* .NET Runtime, CoreCLR or Mono Version: mono 4.4.0
* Fable version: 0.3.15

**Comment by alfonsogarciacaro** [comment]
I haven't used `brunch` but I did get similar reports of problems when using files in a directory external to the project (see #110). To fix that, we added the `--copyExt` argument which will copy the external files into a folder named `fable_external` attaching a hash to prevent name conflicts.

Also because the problem became more common, I set the `--copyExt` argument to `true` by default. Can you please try passing this argument or just updating fable to latest version (v0.3.17)?

BTW, not directly related to the issue but I'll tell you just in case as you're working with import definitions. At the moment, Fable is ignoring all files whose name starts with `Fable.Import` or `Fable.Core` because they're supposed to be _fake_ files just there to provide interface information to the F# compiler. So if you want to have code that's actually compilable, you need to put it in a different file like `Fable.Helpers.React.fs`.

I hope this helps. Cheers!

**Comment by psfblair** [comment]
With Fable 0.3.18 installed I still get the file compiled into the node_modules directory (with just `fable` or with `fable --copyExt`):

```
build/dist/app
...
build/dist/app/Components.js
build/dist/app/Components.js.map
...
build/dist/node_modules
build/dist/node_modules/fable-import-react
build/dist/node_modules/fable-import-react/Fable.Helpers.React.js
build/dist/node_modules/fable-import-react/Fable.Helpers.React.js.map
```
When I looked at the documentation, the --copyExt information didn't immediately suggest itself as a solution to this problem, since it wasn't clear that I should be considering `node_modules` as an directory external to the project. (And in fact from the results above Fable apparently doesn't treat it that way.)

With regard to your last comment -- I was wondering how Fable knew not to compile the interface declaration files to JS. I had all my files compiling, and then just the `Fable.Helpers.React` compiling, and all the other .fs files in the node_modules directory weren't compiling. I had thought there was something wrong until I realized that it was just the interface declaration files that weren't compiling, but I didn't really understand how Fable knew to ignore them.

**Comment by alfonsogarciacaro** [comment]
Thanks for the detailed explanation. I see now that I misunderstood you. Recently, I'm usually putting the F# code in a `src` folder while `node_modules` remains one level above and is thus considered _external_. But in your case `node_modules` is in the same folder as the F# code (which should be a very normal use case) so it's not being tagged as _external_.

I think we should consider any file within `node_modules` always as _external_ so there's no `node_modules` folder generated in the output directory. If you agree with this I'll implement the solution and upload a new version.

Cheers!

**Comment by psfblair** [comment]
I think that's not quite it. Without the workaround I described my overall directory structure looks like this:
```
app/   [Components.fs etc. are here]
brunch-config.js
build/
     dist/
         app/   [Components.js etc. get created here]
         node_modules/
              fable-import-react/  [Fable.Helpers.React.fj gets created here]
     temp/
foo.fsproj
fableconfig.json
node_modules/
      fable-import-react/  [Fable.Helpers.React.fs is here]
package.json
public/
```
This structure comes from my trying to organize the project with several goals:
1. Follow the general standard organization used by brunch, where all source files--js, css, html, etc.--are under an `app/` directory, and ultimately output is generated into a directory called `public/`.
2. Have only one top-level build directory (I've set the .fsproj file so that the output directory is `build/dist` and the intermediate output base directory is `build/temp`).

**Comment by 7sharp9** [comment]
Heres the structure I use for fable-fuse:

```bash
├── App
│   ├── MainView.ux
│   ├── cards-menu.unoproj
│   ├── fonts
│   │   ├── LICENSE
│   │   └── Roboto-Bold.ttf
│   └── js
│       ├── cards-menu.js
│       ├── fable-core.js
│       └── fable_external
│           ├── Apis-1337169215.js
│           ├── Observable-901317181.js
│           └── PromiseExt-2013750498.js
├── build.bat
├── build.sh
├── node_modules
│   ├── fable-core
│   ├── fable-fuse
│   └── fable-import-fetch

├── package.json
└── src
    ├── cards-menu.fs
    ├── cards-menu.fsproj
    ├── fableconfig.json
```

Best thing to do when you get something working it get a yo template going
to it can be easily reused.

You can read about mine for fable-fuse here:
http://7sharpnine.com/blog/fable-fuse-template/

**Comment by alfonsogarciacaro** [comment]
As agreed, I've updated the code so files in `node_modules` are always considered as _external_ and thus copied to the `fable_external` folder. Can you please update `fable-compiler` to version `0.3.20` and check if it's working for you now? If it is, please feel free to close the issue.

Cheers!

**Comment by 7sharp9** [comment]
@psfblair Do you have a sample of the stuff you are working on?

**Comment by psfblair** [comment]
Thanks, Alfonso, this is working for me now!

@7sharp9 Have a look here: https://github.com/psfblair/fable_redux_skeleton . The Redux sample isn't entirely finished yet, but after Alfonso's latest changes I no longer have errors in the console.
