### ISSUE TITLE
Possible type inference bug

### ISSUE THREAD

**Issue by Indy9000** [fsprojects/Fable#189]
### Repro steps
Minimal code to repro

```
type Player ={
  X:float;W:float;
}

type Ball={
  X:float;S:string;
}

let Collide player ball =
  player.X + player.W
```
### Expected behavior
Warning asking for type annotations. 

### Actual behavior
type inferencing of `player.W` in Collide fails with 
`Error Type constraint mismatch. The type     Ball    is not compatible with type    Player    The type 'Ball' is not compatible with the type 'Player'
`
 
### Known workarounds
Types are resolved properly when type annotations are provided.
for example: 
`let Collide (player:Player) (ball:Ball)`

* Operating systems: OSX and Linux
fable-compiler 0.3.17 build

**Comment by alfonsogarciacaro** [comment]
I'm glad you're reporting this here but this is actually an overestimation of Fable's capabilities ;) All code parsing and type resolution is done by the F# compiler. Type inference doesn't work in all the cases and you need to help the compiler with annotations. Particularly, when the parameter is an object type and you want to access a member, as in your example, you usually need the annotations.

Are you using an F# IDE (Xamarin or Visual Studio) or plugin (Ionide for Atom/VS Code or plugins for emacs and Sublime)? If your IDE has support for F# you'll get warnings in real time when the type inference is not working so you know you need to use type annotations.

More info about F# type inference:
https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/type-inference-%5Bfsharp%5D
https://fsharpforfunandprofit.com/posts/type-inference/#not-enough-information

I hope this helps. Cheers!

**Comment by alfonsogarciacaro** [comment]
Closing this issue for now, please feel free to reopen if you have any more questions.
