### ISSUE TITLE
Type error with discriminated union types

### ISSUE THREAD

**Issue by psfblair** [fsprojects/Fable#190]
### Description

Received `TypeError: Cannot read property 'Case' of undefinedexports.inner` at runtime with a pretty simple union type setup.

##### F# code (compiles successfully):

_ActionCreators.fs_
```
module ActionCreators

type ActionType = Increment | Decrement
type Action = { Typ : ActionType }

let increment state = { Typ = Increment }
let decrement state = { Typ = Decrement }
```
_Reducers.fs_
```
module Reducers

module Redux = Fable.Import.Redux
open System
open ActionCreators

let inner = function
    | (state, { Typ = Increment }) -> state + 1
    | (state, { Typ = Decrement }) -> state - 1

let reducer = Func<int,Action,int>(fun state action -> inner (state, action))
```
##### JS code (as compiled):
_Offending line in Reducers.js:_
```
return _arg1 = [_arg1_0, _arg1_1], _arg1[1].Typ.Case === "Decrement" ? (state = _arg1[0], state - 1) : (state = _arg1[0], state + 1);
```
_Full error:_
```
Reducers.js:23 Uncaught TypeError: Cannot read property 'Case' of undefinedexports.inner @ Reducers.js:23exports.reducer @ Reducers.js:27dispatch @ createStore.js:177createStore @ createStore.js:212(anonymous function) @ Initialize.js:43Object.defineProperty.value @ Initialize.js:5(anonymous function) @ Initialize.js:1initModule @ app.js:43require @ app.js:60(anonymous function) @ index.html:10
```
_Reducers.js_
```
(function (global, factory) {
    if (typeof define === "function" && define.amd) {
        define(["exports"], factory);
    } else if (typeof exports !== "undefined") {
        factory(exports);
    } else {
        var mod = {
            exports: {}
        };
        factory(mod.exports);
        global.unknown = mod.exports;
    }
})(this, function (exports) {
    "use strict";

    Object.defineProperty(exports, "__esModule", {
        value: true
    });

    var inner = exports.inner = function (_arg1_0, _arg1_1) {
        var _arg1, state;

        return _arg1 = [_arg1_0, _arg1_1], _arg1[1].Typ.Case === "Decrement" ? (state = _arg1[0], state - 1) : (state = _arg1[0], state + 1);
    };

    var reducer = exports.reducer = (state, action) => {
        return inner(state, action);
    };
});
//# sourceMappingURL=Reducers.js.map
```

### Expected behavior

Should not get a type error. To me the problem looks like the values `_arg1[0]` and `_arg1[1]` are being used before `_arg1` is defined, and instead `_arg1_0` and `_arg1_1` should be referenced. This looks like an issue with the implementation of tuples, which is what is being passed to the function.

### Actual behavior

Got a type error.

### Known workarounds

None as yet.

### Related information 

* Operating system: OS X 10.11.5
* Branch: Fable 0.3.15
* .NET Runtime, CoreCLR or Mono Version: Mono 4.4.0

**Comment by psfblair** [comment]
It looks like the problem is that Redux is dispatching an ActionTypes.INIT when creating the store, and this type doesn't match the action type defined above -- it is necessary that the field be named `type`. Fortunately F# has backticks...

**Comment by alfonsogarciacaro** [comment]
Yeah, I'd like F# didn't care about keywords for member names but unfortunately it's like this at the moment.

I'm glad you fixed the issue. Please tell me if there's anything else I can help you with. Remember we now also have a [Gitter channel](https://gitter.im/fsprojects/Fable) for short questions :+1:
