### ISSUE TITLE
Bug with static members and(?) inlining

### ISSUE THREAD

**Issue by robkuz** [fsprojects/Fable#193]
### Description

I get an runtime crash with the following code which in imo is wrong on the javascript side

### Fsharp Code
```fsharp
type A  = { thing: int } with
    static member show x = x.thing

type B  = { label: string } with
    static member show x = x.label


let inline show< ^T when ^T : (static member show : ^T -> String)> (x:^T) : string =
   (^T : (static member show : ^T -> string) (x))

show { label = "Car" } |> ignore
```
### Javascript Code
```
var A = exports.A = function () {
    function A($arg0) {
        _classCallCheck(this, A);

        this.thing = $arg0;
    }

    _createClass(A, null, [{
        key: "show",
        value: function show(x) {
            return x.thing;
        }
    }]);

    return A;
}();

var B = exports.B = function () {
    function B($arg0) {
        _classCallCheck(this, B);

        this.label = $arg0;
    }

    _createClass(B, null, [{
        key: "show",
        value: function show(x) {
            return x.label;
        }
    }]);

    return B;
}();

new B("Car").show();
```

### Actual behavior

the `_createClass` function creates instance method and not a static member and it should be called as `B.show(new B("Car"))``

### Related information 

* Operating system Max OSX
* Branch Fable 0.3.20
* .NET Runtime, CoreCLR or Mono Version 4.4

**Comment by alfonsogarciacaro** [comment]
Seems `(^T : (static member show : ^T -> string) (x))` is represented in the AST with a [TraitCall](https://github.com/fsharp/FSharp.Compiler.Service/blob/340b9ab6ca1dd90ab7fcd89d503acc4553a3bca9/src/fsharp/vs/Exprs.fsi#L206-L207) that Fable is not resolving properly (because I wasn't sure what it represented). I'll try to ask the F# compiler how these expressions should be dealt with. Thanks for the report!

**Comment by robkuz** [comment]
@alfonsogarciacaro just for clarification: this only happens for `static member`s non static are generated as expected and work as expected
