### ISSUE TITLE
FYI module Node.child_process is masking the globals that are also named Node.child_process

### ISSUE THREAD

**Issue by colinear** [fsprojects/Fable#194]
### Description

expected Node.child_process.spawn to be valid

### Known workarounds
Duplicate the child_process variable in the app
~~~~
#r "node_modules/fable-core/Fable.Core.dll"
open Fable.Core
open Fable.Import

let getStdin (p: Node.child_process.ChildProcess) = p.stdin
let child_process: Node.child_process.Globals = failwith "JS Only" // duplication from Fable.Import.Node.fs
let p = child_process.spawn "ls"
~~~~

**Comment by alfonsogarciacaro** [comment]
This is a bit tricky. I was trying to avoid forcing the user to type `Globals` to access the methods of node modules, by exposing variables with the same name as the module, however this confuses the F# compiler sometimes.

If you open the `open Fable.Import.Node` namespace you don't need to duplicate `child_process`. But of course, not all users would be aware of this, so maybe we should look for a better way to expose node module methods 💭

**Comment by colinear** [comment]
Well, the problem is that I can't get there from here. 

What I get is child_process is bound to the module... this compiles ...
~~~~
#r "node_modules/fable-core/Fable.Core.dll"
open Fable.Core
open Fable.Import.Node
let f (p: child_process.ChildProcess) = ()
~~~~
but this does not ...
~~~~
#r "node_modules/fable-core/Fable.Core.dll"
open Fable.Core
open Fable.Import.Node
let p = child_process.spawn "program"
~~~~
Globals is an abstract type which must be instantiated somehow before it is useful, which is why I used the failWith idiom just like you did. I think the basic problem at the moment is that Fable.Import.Node.fs has both of these statements at top level:
~~~~
module child_process =
~~~~
and
~~~~
let [<Import("*","child_process")>] child_process: child_process.Globals = failwith "JS only"
~~~~
(I would have expected the latter to take precedence, but since it doesn't, I'm not sure this is actually the problem.)

Maybe the module can be named child_process_module or child_process_types.
It took me quite a while to figure out that JS.JSON.parse works but Node.child_process.spawn won't. There isn't a JSON module at top level in Fable.Import.JS.fs.

**Comment by alfonsogarciacaro** [comment]
Interesting, the example above does work for me. Are you on Windows?

```fsharp
#r "node_modules/fable-core/Fable.Core.dll"
open Fable.Core
open Fable.Import.Node
let p = child_process.spawn "program"
```

Probably the best solution is, as you propose, to add a `_module` or `_types` suffix to modules to avoid naming conflicts (I just hope this doesn't confuse users). That, or converting all `Globals` types to static as it's done by default by the `ts2fable` parser. But then you'll be forced to type `Globals` every time you access any module function in node. What do you think?

**Comment by colinear** [comment]
How can I confirm that I am using f# 4 and node 4.4? I installed vs community 2015 with update 2 but I don't actually use it - using vscode with ionide-fsharp and fable -w.

I am on windows 10. I used npm to install fable-compiler 3.20.

Not quite ready for an opinion.

**Comment by alfonsogarciacaro** [comment]
If you have VS 2015 chances are you've F# 4 installed. You can check it by typing `fsc --help` on the terminal. You can also check the node version with `node --version`.

It may be the F# .NET and Mono compilers resolve types a bit differently in this case, but I'm not sure 😕 Anyway, it's probably better to add a suffix to Node modules as discussed. I'll do it.
