### ISSUE TITLE
Array.sort not sorting ints correctly

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fable#197]
### Description

Sorting an array of int sorts by string rather than int

### Repro steps

``` fsharp
[<EntryPoint>]
let main argv =
    let items =
        [| 1;2;10;20 |]
        |> Array.sort

    printf "%A" items
    0
```
### Expected behavior
1, 2, 10, 20

### Actual behavior
1, 10, 2, 20

**Comment by alfonsogarciacaro** [comment]
Sorting is defaulting to the JS native `Array.prototype.sort` which doesn't seem to have the proper behaviour 😕  I've to look into this. Thanks for pointing it out!
