### ISSUE TITLE
Async.FromContinuations fails somehow

### ISSUE THREAD

**Issue by mastoj** [fsprojects/Fable#199]
### Description

When working with my virtual-dom sample I copied the `MailboxProcessor` from Ionide, code is here: https://github.com/ionide/ionide-fsharp/blob/40e518c1f1ea19fd5c9210dcd33059c73b97fd79/src/Core/Control.fs#L62-L139.

Using it in my sample didn't work out of the box. I have already filed one issue, but this one is a little bit more vague of what is wrong. 

### Repro steps

Reproduce it by trying out the `MailboxProcessor`

### Expected behavior

It should work, since it is what is used in Ionide.

### Known workarounds

Change this line: https://github.com/ionide/ionide-fsharp/blob/40e518c1f1ea19fd5c9210dcd33059c73b97fd79/src/Core/Control.fs#L117 from

```
continuation <- Some c
``` 

to 

```
continuation <- Some (unbox c)
```

* OSX
* Master
* Mono: 4.2.1

**Comment by alfonsogarciacaro** [comment]
I cannot find exactly the cause of the problem. I'm fixing several issues now so, when the new version is published (I'll tell you here), can you please give it a try and see if the problem has been magically solved? ;) If not, we'll try to isolate it in a minimal example.

**Comment by alfonsogarciacaro** [comment]
@mastoj, fable-compiler v0.3.24 and fable-core v0.1.9 have been published, including the lightweight version of `MailboxProcessor`. Can you please update both, try again and if it's working now, close the issue? Thanks a lot for your help!

**Comment by mastoj** [comment]
@alfonsogarciacaro I'll try it now. Did you just implement mailboxprocessor with the workaround or did you fix the bug as well? If the bug is still there do you want me to close this issue?

**Comment by mastoj** [comment]
Did try the my mailbox processor with the old code that didn't work. After updating to comply with the types everything worked as expected. Then I commented out the mailboxprocessor in my code and everything still works, so this seems to be fixed. Great work!

**Comment by tpetricek** [comment]
:+1: 

I think the original issue was related to tuples as function arguments (the function was expecting curried arguments but was given tuple, or the other way round).
