### ISSUE TITLE
Cannot find replacement for System.String.trimEnd

### ISSUE THREAD

**Issue by cosinekitty** [fsprojects/Fable#204]
### Description

I have F# code that calls String.TrimEnd(). The code will not build using Fable because it says "Cannot find replacement for System.String.trimEnd".

### Repro steps

Create a file `trimend.fsx` with the following contents:

````fsharp
[<EntryPoint>]
let main argv = 
    let text = "    Hello.    "
    let trimmed = text.TrimEnd()
    printfn "Trimmed text = '%s'" trimmed
    0
````

Try to compile using command `fable trimend.fsx`

### Expected behavior

Should have compiled without errors or warnings. Resulting trimend.js should produce output like this:

````
don@spearmint:~/fable/trimend$ node trimend.js
Trimmed text = '    Hello.'
````

### Actual behavior

````
don@spearmint:~/fable/trimend$ fable trimend.fsx
Start compilation...
Cannot find replacement for System.String.trimEnd (L4,18-L4,32) (/home/don/fable/trimend/trimend.fsx)
````

### Known workarounds

In my particular case, I was able to make the code use String.Trim() instead of String.TrimEnd(). It happened to be OK in my use case, but these functions don't do the same thing, so this is not a general workaround.

### Related information 

* Operating system
````
don@spearmint:~/fable/trimend$ uname -a
Linux spearmint 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
````

* Fable version 0.3.22

* .NET Runtime, CoreCLR or Mono Version
````
don@spearmint:~/fable/trimend$ mono --version
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
````

**Comment by alfonsogarciacaro** [comment]
This should be easy to implement, I'll do it. Thanks for the report!

**Comment by cosinekitty** [comment]
Thanks!  Also just noticed the same problem with String.TrimStart() and System.Char.ToLower(), by the way.  I am very interested in getting some of my F# code to work in a browser environment, so this is an exciting project to find!
