### ISSUE TITLE
Missing support for BigInteger?

### ISSUE THREAD

**Issue by cosinekitty** [fsprojects/Fable#205]
### Description

Trying to use BigInteger (bigint) in an F# program does not seem to be supported by Fable.

### Repro steps

Create file `bigint.fsx` with the following contents:

````fsharp
let x = 123I
let y = 35
printfn "%A ^ %d = %A" x y (System.Numerics.BigInteger.Pow(x,y))
````

### Expected behavior

Should build with no warnings or errors. Should produce the following output (as shown using `fsharpi`):

````
don@spearmint:~/fable/bigint$ fsharpi bigint.fsx
123 ^ 35 = 14017769046734148148805244022693101859937312998675419766920141412796613507
````

### Actual behavior

````
don@spearmint:~/fable/bigint$ fable bigint.fsx
Start compilation...
Cannot find replacement for Microsoft.FSharp.Core.NumericLiterals.NumericLiteralI.fromInt32 (L1,8-L1,12) (/home/don/fable/bigint/bigint.fsx)
````

### Known workarounds

(None known.)

### Related information 

* Operating system
````
don@spearmint:~/fable/trimend$ uname -a
Linux spearmint 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
````

* Fable version 0.3.22

* .NET Runtime, CoreCLR or Mono Version
````
don@spearmint:~/fable/trimend$ mono --version
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
````

**Comment by alfonsogarciacaro** [comment]
Unfortunately there's no support for `bigint` or `decimal` at the moment. We need to add them, but it make some time, as they're actually represented as classes in .NET and all the arithmetic operations must be reimplemented.

**Comment by cosinekitty** [comment]
I would like to volunteer to help implement bigint and decimal support.  I have some experience with implementing high-precision math libraries, and I am motivated to use Fable on my own project called [Freefall](https://github.com/cosinekitty/freefall), which requires bigint. Would you be supportive of me creating a pull request for this?

**Comment by 7sharp9** [comment]
Does it make sense to make bindings for `BigInteger.js` instead?

**Comment by alfonsogarciacaro** [comment]
@cosinekitty, I'll be more than supportive to anyone willing to contribute to Fable with a PR 😄 

@7sharp9, we had a similar discussion when deciding how to add `decimal` to FunScript (which wasn't done at the end 😅). Probably, it would save work to use existing JS libraries for `bigint` and `decimal`. The main problem here is how to include the libraries with the generated code. I can think of three possibilities with their own pros and cons:

1. _Leave the responsibility to the developer_: I then foresee many bug reports because they forget to do it 😉 Maybe we can detect when a lib will be needed and throw a reminder with every compilation.
2. _Add the library directly to the generated code_: the problem then will be duplicity. If you create two packages using `bigint`, each one will include their own copy of the library.
3. _Try to add the reference automatically_: this is complicated because Fable can be used in many environments, as you know very well, loading dependencies in different ways: in the web with `require.js`, in node with `commonjs`, in Fuse...

What do you think? I'm open to any ideas.

**Comment by cosinekitty** [comment]
I know this question wasn't addressed to me, but here's my opinion anyway!  All (supportable) classes from the standard .NET library should come included with Fable.  New users should not have to struggle with the tools to get existing F# building.  This will minimize any adoption barriers for new developers.  Dependencies on external projects create opportunities for things to break at unpredictable times, so I would favor bringing all core functionality under the umbrella of this one project.  Trying to reduce the core library size dynamically would be at the very bottom of my list of priorities: first get stuff working, then optimize if/when it is ever needed.

I'm willing to take on implementing `bigint` and `decimal` types and contribute the code to this project under its existing license.

**Comment by 7sharp9** [comment]
I think that fable should only support a subset just like F# does with android and ios, both of which don't have reflection or bigint.  

FSharp.Core is after all target based and Fable just needs to support a type of footprint, perhaps a Fsharp.Core for Fable is what should be added.  I believe this is the correct course of action as it matches existing logic.

**Comment by alfonsogarciacaro** [comment]
@cosinekitty, the question was not meant for anybody in particular, I'm more than happy to hear everybody's opinion :)

I agree that we should try to support as many classes as possible from .NET, but it's also a matter of resources and what we should prioritise.

In any case, my question wasn't exactly about _whether_ to implement `bigint` but `how` to do implement it. I agree with @7sharp9 that using an existent JS library would save work, I was just wondering how we should add the dependency. I'm considering now that may be we can add `BigInteger.js` as a dependency to `fable-core` so npm will always download them together (if I'm not mistaken, it would be a peer dependency in that case) and then the developer can use a bundler to actually add the library to our app or not depending on whether it's indeed required.

**Comment by alfonsogarciacaro** [comment]
Sorry, I'm closing this as there're no plans to provide support for BigInteger and Decimal at the moment. If you want to give it a shot, please send a WIP PR and we can work together there. Cheers!
