### ISSUE TITLE
Structural Equality Tests does not work for Seq

### ISSUE THREAD

**Issue by robkuz** [fsprojects/Fable#208]
### Description

Structural equality does not work for Sequences but works for Lists

### Repro steps

1. Create code snippet
```fsharp
let result1 = [[1.0; 0.0; 0.0]; [0.0; 1.0; 0.0]] = [[1.0; 0.0; 0.0]; [0.0; 1.0; 0.0]]
let asSeq xs = xs |> List.map List.toSeq |> List.toSeq
let result2 = (asSeq [[1.0; 0.0; 0.0]; [0.0; 1.0; 0.0]]) = (asSeq [[1.0; 0.0; 0.0]; [0.0; 1.0; 0.0]])
```

2. compile with `fable`

3. paste and eval in `fsharpi`

### Expected behavior

`result1` and `result` evaluate to `true`

### Actual behavior

`result1` evaluates to `true``

`result2` evaluates to `false``

### Known workarounds

no know workaround

### Related information 

* Branch 0.3.22

**Comment by alfonsogarciacaro** [comment]
I was adding structural comparison for sequences but then I noticed the example above is a bit misleading. There's actually no structural comparison for sequences. If you replace the lists with arrays `result2` will be false:

```fsharp
let asSeq xs = xs |> Array.map Array.toSeq |> Array.toSeq
let result2 = (asSeq [|[|1.0; 0.0; 0.0|]; [|0.0; 1.0; 0.0|]|]) = (asSeq [|[|1.0; 0.0; 0.0|]; [|0.0; 1.0; 0.0|]|])
```

Same happens if you compare directly lazy sequences:

```fsharp
let result2 = seq{yield seq{yield 1.0; yield 0.0; yield 0.0}; yield seq{yield 0.0; yield 1.0; yield 0.0}} = seq{yield seq{yield 1.0; yield 0.0; yield 0.0}; yield seq{yield 0.0; yield 1.0; yield 0.0}}
```

Not sure why the equality is successful if the sequences are backed by lists, but seems to be something counterintuitive, so I'm not sure it's worth trying to implement this behaviour in Fable.

However, while investigating the issue I've fixed a couple of other minor issues, so the report has been helpful in any case. Thank you!

**Comment by robkuz** [comment]
hmm - that is strange indeed.
As `fsharpi` has the same behaviour I am fine with your decision. Thou I think its worth asking the f# gods why this is so

**Comment by alfonsogarciacaro** [comment]
I guess the equal operator is just calling the `Equals` method of the underlying type, but yes, it can be helpful if you ask the F# team the reasoning behind this :+1:

**Comment by cloudRoutine** [comment]
if you decompile 
```fsharp
let sl1 = seq [ 0..10 ]
let sa2 = seq [|0..10|]
let s   = seq { 0..10 }
```
you see the module's constructor is
```csharp
		static $libb()
		{
			$libb.sl1@3 = Operators.CreateSequence<int>((IEnumerable<int>)SeqModule.ToList<int>(Operators.CreateSequence<int>(Operators.OperatorIntrinsics.RangeInt32(0, 1, 10))));
			$libb.sa2@4 = Operators.CreateSequence<int>((IEnumerable<int>)SeqModule.ToArray<int>(Operators.CreateSequence<int>(Operators.OperatorIntrinsics.RangeInt32(0, 1, 10))));
			$libb.s@5 = Operators.CreateSequence<int>(Operators.OperatorIntrinsics.RangeInt32(0, 1, 10));
		}
```
The array and list are created then cast to their interface, which i guess still allows structural equality whereas the seq cexpr is just creating a lazy enumerator
