### ISSUE TITLE
Fable.Import.Electron.fs npm outdated

### ISSUE THREAD

**Issue by ritcoder** [fsprojects/Fable#218]
### Description

Was testing out the electron sample and got an error with `Electron.EventEmitter`. There seem to be issues with the implementation of `NodeJS.EventEmitter`. 

I thought of doing a PR but realized that it has already been updated so I think it is just the npm package that is not up to date.

### Repro steps

Try the electron sample.

### Expected behavior

No errors

### Actual behavior

Some errors

### Known workarounds

Replace the `Fable.Import.Electron.fs` from the npm package with the one on github

### Related information 

* Operating system
* Branch: 0.3.22
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by alfonsogarciacaro** [comment]
Thanks for the tip! Yes, I need a way to automate the package updates as they're becoming too numerous to manage properly. I've updated `fable-import-electron` to v0.0.5, can you please check if this has fixed the problem? Cheers!

**Comment by ritcoder** [comment]
Did the update and it works. Thanks.
