### ISSUE TITLE
Virtualdom sample doesn't work in safari

### ISSUE THREAD

**Issue by mastoj** [fsprojects/Fable#220]
### Description

The sample page doesn't have the right style on the counter and the todomvc app doesn't work.

### Repro steps

Check the virtualdom sample in safari and compare to chrome and you'll see that the behaviour is correct in chrome but not safari. Not sure what is going on with the styles of the counter, and for the todomvc part it looks like the eventdata isn't sent when the mouse is clicked.

**Comment by alfonsogarciacaro** [comment]
I can confirm that the sample's working now on Safari. Thanks!
