### ISSUE TITLE
fable -w # on win 7 does not watch if started with erroneous code

### ISSUE THREAD

**Issue by colinear** [fsprojects/Fable#226]
### Description

On win 7 at least, the command
~~~~
fable -w
~~~~
generally works, but if the f# program is not error-free when fable starts there is a problem. The problem is that fable never issues the line:
~~~~
Watching D:\Users\user\Desktop\test
~~~~
and does not respond to changes in the fsx file. The fable compiler does not exit.

### Related information 

* win 7 or 10
* 0.3.24

**Comment by alfonsogarciacaro** [comment]
The simplest solution for this was just to finish the process if the first compilation is not successful (errors after that should be recoverable). I hope that's OK.

**Comment by colinear** [comment]
Yes, that helps. Thanks very much.
