### ISSUE TITLE
not detected - warning FS0020: This expression should have type 'unit', but has type ...

### ISSUE THREAD

**Issue by colinear** [fsprojects/Fable#227]
### Description

I don't know if this is a common experience, but in f# I have become accustomed to adding **|> ignore** when calling methods for their side-effects. I do this in response to the following warning that I get when any line of a multi-line function returns other than unit (except of course for the final line.)

~~~~
index.fsx(10,5): warning FS0020: This expression should have type 'unit', but has type 'int'. Use 'ignore' to discard the result of the expression, or 'let' to bind the result to a name.
~~~~

### Repro steps
~~~~
#r "node_modules/fable-core/Fable.Core.dll"
open Fable.Core
[<Emit ("function jsOnly () {}")>]
let jsOnly () =
    printfn "Exiting ... only the javascript product of this fable app is intended to run"
    System.Environment.Exit 0
jsOnly ()

open Fable.Import
let [<Global>] G: obj = failwith "JS Only"
let f () =
    G $ 1
    ()
f ()
~~~~
### Expected behavior
Something like fsi:
~~~~
index.fsx(12,5): warning FS0020: This expression should have type 'unit', but has type 'obj'. Use 'ignore' to discard the result of the expression, or 'let' to bind the result to a name.
~~~~

### Actual behavior

No warning is issued

### Related information 

* win 7
* 0.3.24

**Comment by alfonsogarciacaro** [comment]
This is related to #225 and should be fixed in the newly published v0.3.25. Could you please give it a a try and reopen the issue if it's still failing? Please also update `fable-core` to v0.1.10 to check #222. Cheers!

**Comment by alfonsogarciacaro** [comment]
Sorry, there was a problem with v0.3.25, please use v0.3.26 instead.

**Comment by colinear** [comment]
compiler warnings working as expected in 0.3.26 with fable-core 0.1.10
