### ISSUE TITLE
Typescript2Fable - Namespaces

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/Fable#23]
Let's consider following typescript definition:
```
declare namespace vscode {
    export interface TextEditor {
        something : string
    }

    export namespace commands {
        export function something2(texteditor : TextEditor) : string
    }

}

declare module 'vscode' {
	export = vscode;
}
```

We get following F# output:
```
namespace Fable.Import
open System

module commands =
    type private ImportAttribute(path) =
        inherit System.Attribute()





    type Global =
        abstract something2: texteditor: TextEditor -> string

    [<Import("commands")>]
    let Global: Global = failwith "JS only"

module vscode =
    type private ImportAttribute(path) =
        inherit System.Attribute()

    and TextEditor =
        abstract something: string with get, set




module vscode =
    type private ImportAttribute(path) =
        inherit System.Attribute()
```
1. We get duplicated `vscode` module which is not valid F# code
2. Module `commands` is not nested into vscode module - it may or may not be right solution but if it's desired behavior `TextEditor` type is not accessible from commands module - should be used `vscode.TextEditor` (and right ordering of modules)

**Comment by cloudRoutine** [comment]
something this could work
```fsharp

namespace global

[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module vscode = 
    let modulebinding = "module"

namespace vscode

module nested = let x = "inside"


namespace test

module testing = 
    let z = vscode.modulebinding
    let y = vscode.nested.x
```
The module needs to be declared before the namespace and the module must have the `[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]` attribute

otherwise 

![](http://i.imgur.com/yjYrG9p.png)

![](http://i.imgur.com/rq2eATh.png)

**Comment by alfonsogarciacaro** [comment]
The nested modules issue has been fixed (though the Import attribute needs yet to be adjusted). I have uploaded a file with the parsed definition for vscode [here](https://github.com/fsprojects/Fable/blob/master/lib/Fable.Import.VSCode.fs). I tweaked it by hand but some things may still be missing (like enums). Can you please check? Thanks!

**Comment by Krzysztof-Cieslak** [comment]
Enums are missing indeed, but generally it's getting better and better. I would like get process full automated (no by hand changes required) even if output bindings are not perfect. Then we would have some base to build on and we could easy re-generate bindings as things will be updated.
