### ISSUE TITLE
Using Vue js framework with fable can yield wrong result for equality of values

### ISSUE THREAD

**Issue by markek** [fsprojects/Fable#233]
### Description
I have a fable browser app with something like
~~~~
type T = A | B | C | D
let x = A
let b = if x = A then true else false
~~~~
and b incorrectly evaluates to false. The js is calling _fableCore.Util.compareTo.  The obvious use of match produces the correct answer - in that case the js just compares the Case field.

### Repro steps

Not easy to determine. I spent 10 minutes on a minimal test case but it passed. That test happened to be for node and not the browser. I wanted to post this possible issue before I spent the time to tear down and sanitize my app into a test case. The actual union type is just four labels, so I was surprised when my (node) test case passed.

Fyi on the node side I am using npm deeper for comparing js objects that are parsed from json.

### Related information 

* win7/firefox
* 0.3.26, fable-core 0.1.12

**Comment by alfonsogarciacaro** [comment]
Not sure if that's the reason, but `fable-core` uses some ES6 features that may not be available in the browser. Are you loading `core-js`? If not, can you please do it and check if it works? More info [here](http://fsprojects.github.io/Fable/docs/compiling.html#Polyfill).

Cheers!

**Comment by colinear** [comment]
I did confirm core-js. I reduced my app until it was very small. Then I switched from using Vue to just using console.log, and it started working. Perhaps Vue or VueHelper is adding reactivity to the object that make it unequal to the fresh reference object used for comparison.

**Comment by alfonsogarciacaro** [comment]
Yes, [Vue modifies JS objects](http://vuejs.org/guide/reactivity.html#How-Changes-Are-Tracked). It's a library I like very much and I try to adapt Fable to it at first (see the [vue-todomvc sample](https://github.com/fsprojects/Fable/tree/master/samples/browser/vue-todomvc)) but because of this kind of tricks it uses, there're many cases where interaction becomes difficult 😕 I don't think we can easily fix this, but any suggestion is welcome. Also, please feel free to close the issue if you think it's OK.

**Comment by colinear** [comment]
Well, funny thing - it was your sample that got me started using Vue. The Vue part of my app doesn't have user interaction - basically a signage screen with the only input coming from a network source (fable/node/mqtt), so it has served me well.

Let me think about this a little bit before closing this.

**Comment by alfonsogarciacaro** [comment]
Sorry, I'm closing the issue as it's a bit old. Please feel free to reopen it if you find a way to better interact with Vue from Fable.
