### ISSUE TITLE
Can't transpile .fsproj files

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/Fable#235]
### Description

I can't transpile a .fsproj file. However I can transpile a .fsx file.

Here is the output of my command:

```
C:\Users\mmangel\Documents\0-Personnel\SquiibzSuave\Browser>fable Browser.fsproj
 --verbose --outDir out
Fable F# to JS compiler version 0.3.26
PROJECT FILE: C:\Users\mmangel\Documents\0-Personnel\SquiibzSuave\Browser\Browse
r.fsproj

OUTPUT DIR: C:\Users\mmangel\Documents\0-Personnel\SquiibzSuave\Browser\out

WORKING DIR: C:\Users\mmangel\Documents\0-Personnel\SquiibzSuave\Browser

FABLE COMMAND: cmd /C C:\Users\mmangel\AppData\Roaming\npm\node_modules\fable-co
mpiler\bin\Fable.Client.Node.exe --copyExt true --projFile Browser.fsproj --verb
ose true --outDir out --ecma es5 --module umd

Start compilation...
[INFO] Warmup: 2.145681s
```

[Here](https://1drv.ms/u/s!Ah3mucpod966getCnpoWax6hEl6RJA) is a zip file containing my project.

The commands used are:

`fable Browser.fsproj --outDir out`
`fable canvas.fsx --outDir out`

Ps: I renamed `fableconfig.json` to `fableconfig2.json`

**Comment by alfonsogarciacaro** [comment]
I checked your project, it seems it contains only one file: `Program.fs`

```xml
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="Program.fs" />
    <None Include="App.config" />
    <None Include="package.json" />
  </ItemGroup>
```

However the file in the folder is named `Main.fs`. If you change the name (and add the `Fable.Core.dll` reference) it works. Probably Fable should give a warning when files are not found.

**Comment by MangelMaxime** [comment]
Oh right... didn't suspected that the renaming has gone wrong. Thanks for your help.
