### ISSUE TITLE
Build artifacts should be in /build

### ISSUE THREAD

**Issue by fdcastel** [fsprojects/Fable#244]
Currently all F# binaries created from `/src/plugins` are being put in the same folder as its sources.

Ideally, the build process should keep the entire `/src` folder untouched. And all its generated artifacts should end in a different folder (`/build/plugins` in this case).

Since you already doing a major refactor (nice work, BTW :+1:) we could also consider this minor change... :wink: 

BTW: In the tutorial update from #243 I changed the paths to reflect the _current_ output folder (in `/src/plugins/random`). If we made this change, we should update it again to `/build/plugins/random`.

**Comment by alfonsogarciacaro** [comment]
At the moment only `plugins/nunit` is an npm package, but other plugins should become packages as well, and moving the `dll` to `build` means that we also have to copy the other files to publish the package (at a minimum `package.json` and `readme.md`). This is done for `fable-compiler` but only for that. It could a bit tedious to do it for all the other packages: `fable-core`, import packages, samples, plugins, providers... What do you think?

**Comment by fdcastel** [comment]
Hm. I see...

While now I regret the use of "minor" in the original post ;) I do think yet that a clean build process should not touch `/src` folder anyway. 

Anyway, this is just me being perfectionist. After all, pragmatically speaking, there's no problem at all with the current build system. :wink:

I'll think more about it tomorrow. :+1:
