### ISSUE TITLE
Possible codegen error for overloaded operator with a primitive type as first arg

### ISSUE THREAD

**Issue by Indy9000** [fsprojects/Fable#246]
`static member (*)(a,v:Vector) = Vector(a*v.x, a*v.y)` produces wrong code

repro code
```
type Vector(x:float,y:float) =
  member this.x = x
  member this.y = y
  //static member inline (+)(v1:Vector,v2:Vector) = Vector(v1.x+v2.x,v1.y+v2.y)
  static member (*)(v:Vector,a) = Vector(a*v.x, a*v.y)
  static member (*)(a,v:Vector) = Vector(a*v.x, a*v.y)

let a = Vector(1.0,2.0)
let b = Vector(2.0,1.0)
let v1 = 2. * a;
let v2 = b * 3.;

printf "%A" v1
printf "%A" v2
```

generates the wrong code for `v1`

```
  var Vector = exports.Vector = function () {
    function Vector(x, y) {
      _classCallCheck(this, Vector);

      this["x@6"] = x;
      this["y@6"] = y;
    }

    _createClass(Vector, [{
      key: "x",
      get: function () {
        return this["x@6"];
      }
    }, {
      key: "y",
      get: function () {
        return this["y@6"];
      }
    }], [{
      key: "op_Multiply",
      value: function op_Multiply(v, a) {
        return new Vector(a * v.x, a * v.y);
      }
    }, {
      key: "op_Multiply_1",
      value: function op_Multiply_1(a, v) {
        return new Vector(a * v.x, a * v.y);
      }
    }]);

    return Vector;
  }();

  _fableCore.Util.setInterfaces(Vector.prototype, [], "App.Vector");

  var a = exports.a = new Vector(1, 2);
  var b = exports.b = new Vector(2, 1);
  var v1 = exports.v1 = 2 * a;
  var v2 = exports.v2 = Vector.op_Multiply(b, 3);

```

resulting in nulls. 
```
printf "%A" v1
printf "%A" v2
```
```
null
app.fsx:23 {"x@6":6,"y@6":3}
```

Expected:
Correct code or warning if this is not yet supported.

**Comment by alfonsogarciacaro** [comment]
For custom operators I was just checking the first argument in the naive assumption it would always be the same as the second one :/ This must be fixed, thanks for the report!

**Comment by alfonsogarciacaro** [comment]
Unfortunately this has proven to be trickier than I expected. Checking the type where the operator is coming from is difficult when it's not the same as the first operand. Also, in your example there are two implementations for `*` and overload resolution for custom operators is problematic as well in Fable's current state 😞 

For now, I'm just disallowing this behaviour and throwing a compile type error message, so the user knows what must be fixed. I hope that's ok but please tell me otherwise.

**Comment by alfonsogarciacaro** [comment]
Thanks to modifications of Fable AST in the latest version, now it's possible to use overloaded custom operators! 🎉 It's also OK to put the type holding the operator as second argument. Can you please give it a try with fable-compiler/fable-core 0.5.1 and check if it works for you? Thanks!
