### ISSUE TITLE
Please upgrade fable-compiler package: ^0.4.0-alpha

### ISSUE THREAD

**Issue by everystone** [fsprojects/Fable#254]
### Description

The samples requires fable v 0.4.0-alpha, but latest on npm is 0.3.26

### Repro steps

C:\Users\eirik\Downloads\samples\browser\mario>fable
Fable version: 0.3.26
Required: ^0.4.0-alpha
Please upgrade fable-compiler package

C:\Users\eirik\Downloads\samples\browser\mario>npm info fable-compiler version
0.3.26

Where can I find version 0.4.0-alpha?

Cheers

**Comment by alfonsogarciacaro** [comment]
As it's a prerelease you need to install it with the specific name: `npm install fable-compiler@0.4.0-alpha` (add `--global` if you want to install it globally).

The alpha version is also tagged as `next`, so this works too: `npm install fable-compiler@next`

Have fun!

**Comment by everystone** [comment]
Thank you!
