### ISSUE TITLE
"arguments" is not a valid JS variable name

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/Fable#258]
When you have a variable `arguments` you get an error:

> some.js:156 Uncaught SyntaxError: Unexpected eval or arguments in strict mode

I had this in a more complex context, but I think the following is sufficient repro:

```fsharp
let foo x = 
  match x with
  | Some(arguments) -> 0 
  | _ -> 1
```

I'm not sure what is the current approach to renaming invalid JS names, but a warning would be nice.

**Comment by alfonsogarciacaro** [comment]
Damn, I forgot to add it [here](https://github.com/fsprojects/Fable/blob/master/src/fable/Fable.Core/Util.fs#L71). Hopefully it should be add simple as adding it to the list of js keywords. Thanks for the report!
