### ISSUE TITLE
Hot code reloading for virtualdom

### ISSUE THREAD

**Issue by mastoj** [fsprojects/Fable#262]
Feature req. for the virtualdom import. Hot code reloading is present in both react and elm, so I think it should be possible for virtualdom.

**Comment by mastoj** [comment]
I have no idea how this would work, but it would be nice to fire up a suave server that could compile sources and the fly and act as a proxy or something. For that to work it must be possible to run fable from .net.

**Comment by alfonsogarciacaro** [comment]
It is already possible to call Fable from .NET just creating a command process as it's done in the build script. There's also a Fable.Client.Suave project which was planned to be used in the online REPL but it needs working after the refactoring. It's planned to create another client that can be used as a library from .NET, however I have other priorities at the moment so I don't have a date for that :/

In any case, it depends on what you exactly understand by hot code reloading:
- __Recompile code on changes__: This is already implemented by Fable using the `--watch` option.
- __Refresh the browser after recompilation__: This can be achieved in several ways. The most common one is using web sockets from the server (which a minimal static server) and inject a few lines to the client JS code to reload the page when receiving a "refresh" message or similar.
- __Replace the JS code without refreshing the browser__ (Hot Module Replacement): This is really complicated and, AFAIK, Webpack is the only tool implementing this. In theory it should work almost out of the box when using the Webpack development server. But I think the components that are supposed to update more frequently must appear in their own file(s).

**Comment by mastoj** [comment]
No worries, I just put it here as a future feature that would be nice. I was thinking of the last point with refreshing the js but keeping the state in the browser. I've only played with that feature in react, but it was a really nice flow. I could try to add the webpack devserver and see if it works out of the box.

**Comment by alfonsogarciacaro** [comment]
I think at least you must move [this part](https://github.com/fsprojects/Fable/blob/master/samples/browser/virtualdom/virtualdom.fsx#L395-L408) to a different file to prevent webpack from reloading the full page.

**Comment by alfonsogarciacaro** [comment]
Sorry, I'm closing this as this won't probably be a Fable feature. I think it's already possible to hot reload the virtualdom sample as commented above. And in the case some specific tooling would be necessary, this will probably have to be developed independently from Fable main code.
