### ISSUE TITLE
StackOverflowException during AppVeyor build

### ISSUE THREAD

**Issue by krgn** [fsprojects/Fable#263]
### Description

Building my `FAKE`-based project in `AppVeyor` results in a `StackOverflowException`. The same build runs fine on my Linux-based machine using `Mono`. 

### Related information 

* Fable Version: 0.3.26
* AppVeyor Windows Image

**Comment by krgn** [comment]
![2016-07-15-191216_1518x861_scrot](https://cloud.githubusercontent.com/assets/422437/16892224/e637515c-4ac0-11e6-9a13-ea4a50e80270.png)

**Comment by alfonsogarciacaro** [comment]
I guess your development machine is also Linux/OSX, right? Is it your project public? If it is, it would be very helpful to try to reproduce the error.

In any case, can you please also try with fable-compiler@0.4.0-alpha and fable-core@0.2.0-alpha? Also, if you use the --verbose option with Fable, you will get the full Stack Trace of the error.

I hope this helps!

**Comment by krgn** [comment]
Thank you, I'll give it a shot!

**Comment by krgn** [comment]
`0.4.0-alpha` indeed solves the problem! Thanks for your help!
