### ISSUE TITLE
build FableCore fails because of missing plugin

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/Fable#264]
I mentioned this on the Gitter, but just for the record, when you run `build FableCore`, you currently get the following error (on Windows 8.1):

    > babel "fable-core.js" "-o" "commonjs.js"

> ReferenceError: Unknown plugin "transform-es2015-modules-commonjs" specified in
"C:\\Tomas\\Public\\fsprojects\\Fable\\src\\fable\\Fable.Core\\npm\\.babelrc.env
.target-commonjs" at 0, attempted to resolve relative to "C:\\Tomas\\Public\\fsp
rojects\\Fable\\src\\fable\\Fable.Core\\npm"

I do have global install of `bable-cli`, but I guess that's not needed anymore. (It might be, however, overriding some locally installed better version?)

**Comment by fdcastel** [comment]
I believe you found the root cause in #265 :wink: 

This always occurs to me after a full `build`. It brokes `build fablecore`. 

The (workaround) solution it to delete all `node_modules` folder in `Fable.Core/npm` and run a `npm install` again.

**Comment by alfonsogarciacaro** [comment]
I added the missing plugins to package.json, this should fix the issue :+1: Please reopen the case if you're still having problems.
