### ISSUE TITLE
win7 samples/node/express compiler produces FABLE ERROR: ...

### ISSUE THREAD

**Issue by markek** [fsprojects/Fable#273]
### Description
Tried compiling my fsx project and got this error. Then tried fresh pull of samples/node/express and got same error. I noticed that the node/console project does compile. One difference between them is that the latter uses fsproj and the former uses fsx.

### Repro steps

npm install -g fable-compiler
cd samples/node/express
fable

### Expected behavior
~~~~
successful compilation
~~~~
### Actual behavior
~~~~
npm install
Start compilation...
FABLE ERROR:
...
~~~~
### Related information 

* Fable Version 0.4.1
* win7

**Comment by MangelMaxime** [comment]
This is the behavior that I encounter yesterday on my computer at work.

Here is the result if I try to execute the FABLE COMMAND manually, I got this error

```
System.Exception: Cannot read project options: Cannot load the file or assembly 'Microsoft.Build.Framework, Version=12.0.0.0
, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of it dependencies. The file specify is not found.
   à Fable.Client.Node.Main.getProjectOpts@101.Invoke(String message)
   à Fable.Client.Node.Main.getProjectOpts(FSharpChecker checker, CompilerOption
s opts)
   à Fable.Client.Node.Main.main(String[] argv)
```

Sorry if the error is not the exact message. My computer at work is in french.

As @colinbull mention that he has been able to build .fsproj and not .fsx file, I tested both with the same code and I confirm this situation too.

**Comment by alfonsogarciacaro** [comment]
I cannot reproduce the problem in Windows 10, but in any case I have released fable-compiler@0.4.2 using again the Nuget version of FSharp.Compiler.Service instead of the custom build. Could you please give it a try with the new version and confirm if the problem has been solved? Thanks!

**Comment by MangelMaxime** [comment]
The new version didn't fix this issue.

I think that you can't reproduce this issue under Windows 10, because it's "specific" to Windows 7. I mean at home I am working with Windows 10 without problem and here at work under Windows 7 I got the error.

**Comment by alfonsogarciacaro** [comment]
Probably the error is coming from FSharp.Compiler.Service then, I'll report it there. The alternate solution is that we all update to Windows 10 😉

**Comment by MangelMaxime** [comment]
If only I could at work :)

Thanks.

**Comment by alfonsogarciacaro** [comment]
What .NET version do you have installed on the Win7 system?

**Comment by MangelMaxime** [comment]
Hum the default one installed with Visual Studio 2015.

Should be .Net 4.5/4.6, I think.

**Comment by alfonsogarciacaro** [comment]
I've published fable-compiler@0.4.3. This just has a fix to be able to visualise the stack trace of the problem. Can you please try again with the new verbose and post here the error stack trace? Thanks!

**Comment by MangelMaxime** [comment]
Sure, but I cannot do it before Monday. I will post the result here later so.

**Comment by markek** [comment]
Ok, I am using a fresh aws workspace for my computer. It isn't win 7 but it is:
64-bit dual core - windows server 2008 r2 data center sp1 - with a win 7 experience.
Note the user's desktop is on a D: drive.
I installed vs community with updates, custom install, check f# language.
I installed node v4.4.7 lts 64-bit.
I downloaded fable-master.zip, unzipped and went to samples/node/express

Results:
~~~~
fable --verbose

Fable F# to JS compiler version 0.4.3
npm install

PROJECT FILE: D:\Users\mark\Desktop\Fable-master\Fable-master\samples\node\expre
ss\index.fsx
OUTPUT DIR: D:\Users\mark\Desktop\Fable-master\Fable-master\samples\node\express
\out
WORKING DIR: D:\Users\mark\Desktop\Fable-master\Fable-master\samples\node\expres
s

FABLE COMMAND: cmd /S /C "D:\Users\mark\AppData\Roaming\npm\node_modules\fable-c
ompiler\bin\Fable.Client.Node.exe --copyExt true --verbose true --module commonj
s --sourceMaps true --projFile ./index.fsx --outDir D:\Users\mark\Desktop\Fable-
master\Fable-master\samples\node\express\out --ecma es5"

Start compilation...
ERROR: Cannot read project options: Could not load file or assembly 'Microsoft.B
uild.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a
3a' or one of its dependencies. The system cannot find the file specified.
   at Fable.Client.Node.Main.getProjectOpts@101.Invoke(String message)
   at Fable.Client.Node.Main.getProjectOpts(FSharpChecker checker, CompilerOptio
ns opts)
   at Fable.Client.Node.Main.main(String[] argv)
~~~~

**Comment by alfonsogarciacaro** [comment]
Thanks! Now we have more information to deal with the problem :+1: Can you please try installing [MSBuild tools 2013](https://www.microsoft.com/en-us/download/details.aspx?id=40760)?

**Comment by MangelMaxime** [comment]
For me it's working now using MSBuild tools 2013.

**Comment by markek** [comment]
For me also. Thanks very much.

**Comment by alfonsogarciacaro** [comment]
Fantastic! Thanks you both for your help and patience checking the issue. Hopefully, people with the same problem will find this when searching a solution. Actually, @MangelMaxime already had shown the solution when posting the error message on his first comment, but for some reason I missed that 😕

**Comment by WilliamBerryiii** [comment]
Should this get added to a getting started guide?  Just ran into this with a demo node project.

**Comment by jimfoye** [comment]
I know this is closed, but I'm just curious, why is it necessary to install Microsoft Build Tools 2013 if we already have VS 2015 installed?

**Comment by tpetricek** [comment]
It is an old issue in the F# Compiler Service (FCS) (https://github.com/fsharp/FSharp.Compiler.Service/issues/631) which Fable uses - but fortunately, it should be fixed soon, because the issue has recently been addressed in FCS (https://github.com/fsharp/FSharp.Compiler.Service/pull/649)!
