### ISSUE TITLE
Array.mapFold missing

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fable#274]
When using Array.mapFold you get the following error message:

```
ERROR: Cannot find replacement for Microsoft.FSharp.Collections.Array.mapFold 
```

**Comment by fdcastel** [comment]
Working on it... :wink:

**Comment by fdcastel** [comment]
Uh... sorry @davidtme : but where is this function?

https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/collections.array-module-%5bfsharp%5d

**Comment by fdcastel** [comment]
Doh. Found it:

https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSharp.Core/array.fs

Never believe in the docs :sweat_smile:

**Comment by fdcastel** [comment]
That should do it. Have a great weekend, guys!

**Comment by alfonsogarciacaro** [comment]
fable-compiler@0.4.4 and fable-core@0.2.3 have been released with the fix :+1:
