### ISSUE TITLE
How do you keep Fable imports up-to-date?

### ISSUE THREAD

**Issue by forki** [fsprojects/Fable#281]
Is tehre a (fake) script that keeps the fable imports up-to-date?
Is there a chance to add react-native and things like react-native-* (like react-native-camera)?

**Comment by Krzysztof-Cieslak** [comment]
1. Running `npm update` updates scripts to latest version (respecting restrictions specified in `package.json`)

2. I'll PR react-native soon

**Comment by alfonsogarciacaro** [comment]
To be honest, my initial hope was that import packages were community maintained :wink: (As the TypeScript declaration files actually are). Probably I'll move them soon from Fable's repo as they add a lot of maintenance overhead (checking correctness of the declaration file, keeping them in sync with API updates, etc...). @mastoj suggested to have each import in its own repo once a Fable Github organisation is created, or maybe we can try to emulate DefinitelyTyped. I'm open to suggestions 😄 

As react-native bindings have been mentioned, I'm adding a reference to issue #228.

**Comment by forki** [comment]
So I guess my question is: given there is a tool that can convert typescript definitions to fable, why can't we automate this to do it over everything in definitelytyped?

**Comment by alfonsogarciacaro** [comment]
Because unfortunately the parser is not perfect and most of the times manual tweaks are needed :disappointed: FunScript actually managed to parse all the declarations in DefinitelyTyped but it was in the early stages of TypeScript when the type system was much, much simpler.

Now TypeScript AST is very complex and poorly documented (and it may change a lot in the new versions). The code of the `ts2fable` parser is quite messy and full of hacks. I tried to use TypeScript [type checker](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker) to make things more systematic but failed miserably.

**Comment by forki** [comment]
Ok thanks for clarification. It's what I assumed ;-)

**Comment by mastoj** [comment]
I definitely think that the way fable grows justifies for a separate fable org. This will give:

* More fine grained control, not everyone need to have access to the core stuff when just working with an import
* More focus of what should be in core.
* Easier for others to see how to create their own import. We could even give them a minimum template for creating a new import or whatnot.

**Comment by MangelMaxime** [comment]
I like the idea to have one repo by import. Because, for me it's better to maintain them and this don't create a mess of commits when we modify another import.

**Comment by alfonsogarciacaro** [comment]
Yeah, we should move to our own organisation. For that we need the logo (#183). We wanted to hire the designer of Suave's logo but unfortunately she's not available. Now we're thinking to try [99designs](https://99designs.com), but if someone else have any other idea, please shoot :gun:

**Comment by forki** [comment]
concrete example: where would we put https://github.com/Krzysztof-Cieslak/fable-react_native-demo/blob/Picker/src/Fable.Import.ReactNativeImageCropPicker.fs ?

**Comment by alfonsogarciacaro** [comment]
I guess that would go in a `fable-import-react-native` repo within the Fable organisation (together with `package.json` and `README.md` files for publishing in npm).

**Comment by alfonsogarciacaro** [comment]
Closing the issue as we already have #183 to track the creating of own GH organization.
