### ISSUE TITLE
Using flexible types (#type) for generated bindings.

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/Fable#283]
Because of weaker type system in TS, people tends to use inheritance a lot in their definition files, it produces F# code using also lot of inheritance in Fable-generated bindings... which is not super nice too use in general, and requires lot of casting. 

For any functions and member methods we could use `#custom_type` to accept any type inheriting from `custom_type`

**Comment by alfonsogarciacaro** [comment]
That's an interesting idea. Could you please provide some example code to illustrate the problem and how the proposed solution would solve it? Ideally, also with an indication of what the TS parser should do to implement this.

Please also note that upcasts are erased from the compiled code so this would just an inconvenience when programming but with no runtime effects.

**Comment by alfonsogarciacaro** [comment]
Sorry, I'm closing this for now. Please feel free to reopen it if there's additional info that could help to solve the problem. Cheers!
