### ISSUE TITLE
How to set parameters?

### ISSUE THREAD

**Issue by forki** [fsprojects/Fable#288]
type ImagePicker =
        abstract member showImagePicker: (ImagePickerOptions * (ImagePickerResult -> unit)) -> unit

renders to

    $import1.showImagePicker([p, result => {}]);

why is the array generated? I would expect

    $import1.showImagePicker(p, result => {});

**Comment by alfonsogarciacaro** [comment]
Apparently the F# compiler is interpreting that you're passing an actual tuple to the method (maybe because of the parens in the signature) which Fable translates to JS arrays.

**Comment by forki** [comment]
right. without parens it works as well. thx
