### ISSUE TITLE
Show message when ready

### ISSUE THREAD

**Issue by forki** [fsprojects/Fable#289]
I'm using fable for react native and can't really see when fable is done. Can you please add a ready meesage at end?

**Comment by alfonsogarciacaro** [comment]
Can you please give more detail about how are you using fable (e.g. are you using the `--watch` option?) and what exactly you would like to see. Right now, you get a message every time a file is compiled and if you're not using the `--watch` option the process just stops when finished (or calls the `postbuild` script):

```
MacbookPro:Fable alfonsogarciacaronunez$ fable samples/browser/pacman/
npm install
Start compilation...
Compiled pacman.fsx at 4:04:52 PM
MacbookPro:Fable alfonsogarciacaronunez$ 
```

**Comment by forki** [comment]
thx for telling me about --watch.

this is great. :kiss:
