### ISSUE TITLE
Watch throw "ERROR: Value cannot be null." error

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fable#295]
I haven't been able to get --watch working. I'm not sure if its something I've added to my code or an update to fable but I'm now getting an error.

I can get everything to compile:
```
C:\Dev\game2\src\Client>node ./node_modules/fable-compiler/index --symbols FABLE --watch
Start compilation...
Compiled fable_inject.js at 3:03:33 PM
Compiled Fable.Helpers.ReduxHelper.fs at 3:03:33 PM
Compiled Models-586677941.fs at 3:03:33 PM
Compiled Helpers-1239822851.fs at 3:03:33 PM
Compiled Models.Frontend.fs at 3:03:33 PM
Compiled Renderer.fs at 3:03:34 PM
Compiled MapLayer.fs at 3:03:34 PM
Compiled InterfaceActions.fs at 3:03:34 PM
Compiled Helpers.fs at 3:03:34 PM
Compiled Client.fs at 3:03:34 PM
Watching C:\Dev\game2\src\Client
```

but then when I update a file I get the following:

```
rename: Renderer.fs at 3:03:38 PM
ERROR: Value cannot be null.
Parameter name: path
```

I've added some extra logging into fable.js(L287) which returns the following:

```
{ type: 'ERROR',
  message: 'Value cannot be null.\r\nParameter name: path',
  stack: '   at System.IO.Path.GetFullPathInternal(String path)\r\n   at Fable.FSharp2Fable.Compiler.IsMasked@919.Invoke(String key, FSharpList`1 deps)\r\n   at Microsoft.FSharp.Collections.MapTreeModule.existsOpt[a,b](FSharpFunc`3 f, MapTree`2 m)\r\n   at Microsoft.FSharp.Collections.MapTreeModule.existsOpt[a,b](FSharpFunc`3 f, MapTree`2 m)\r\n   at Microsoft.FSharp.Collections.IEnumerator.next@224[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0)\r\n   at Microsoft.FSharp.Collections.IEnumerator.filter@219.System-Collections-IEnumerator-MoveNext()\r\n   at Microsoft.FSharp.Collections.IEnumerator.choose@202.System-Collections-IEnumerator-MoveNext()\r\n   at Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@542-1.Invoke(Unit unitVar0)\r\n   at Microsoft.FSharp.Collections.Generator.appG[a](Generator`1 g)\r\n   at Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator`1.System-Collections-IEnumerator-MoveNext()\r\n   at Microsoft.FSharp.Collections.IEnumerator.map@111.DoMoveNext(b& )\r\n   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()\r\n   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)\r\n   at Fable.Client.Node.Main.compile(ICompiler com, FSharpChecker checker, FSProjectInfo projInfo)' }
```

**Comment by alfonsogarciacaro** [comment]
It seems a null values is being passed [here](https://github.com/fsprojects/Fable/blob/master/src/fable/Fable.Compiler/FSharp2Fable.fs#L896) but I wonder why. It's also strange that when you update the file the event is `rename` (should be `change`). Are you just editing and saving the file or do you rename, move it? Also, you're on Windows right? (I heard that node's default watcher doesn't work well on Windows, maybe we should use another tool).

**Comment by davidtme** [comment]
Yeah, I'm on windows. I'm editing, saving the file in VS2015. Oddly if I edit the file in a different editor (Say VS Code) I get:
```
Watching C:\Dev\game2\src\Client
change: Renderer.fs at 3:44:28 PM
ERROR: Value cannot be null.
Parameter name: path
```

**Comment by davidtme** [comment]
I have a feeling it's todo with the fable_inject.js (or plugins).  If I remove the "plugins" from my fableconfig.json the watch springs back into life.

**Comment by alfonsogarciacaro** [comment]
Perfect, thanks for the info :+1: I'll try to reproduce the problem creating a project with some code injections.

**Comment by alfonsogarciacaro** [comment]
Ok, this happened because I was sloppy and used `null` for a string value instead of `None` (this is supposedly why we program in F#, right? :wink:). It should be fixed now in master, could you give it a try?

**Comment by davidtme** [comment]
That seems to have done the trick,  Thanks for your help.
