### ISSUE TITLE
GenerateDocs fails on NUnit demo

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/Fable#310]
`build GenerateDocs` fails (on my machine) when processing the NUnit demo. The error message I get is:

> ERROR: Error in plugin Fable.Plugins.NUnit: Method not found: 'System.String Context.get_file()'. ((L92,0-L92,49)) (c:\...\samples\node\nunit\index.fsx)
Running build failed.

> Error: System.Exception: 'c:\Tomas\Public\fsprojects\Fable> node build/fable samples/node/nunit -o ../../../temp --symbols TUTORIAL' task failed

This is using the latest Fable when building from the source (as of yesterday) on Windows 8.1. I run `build All` before running `build GenerateDocs`.

It sounds like something that might be caused by a mismatching version of `Fable.Core.dll` - perhaps the locally built version needs to be copied somewhere else?

**Comment by alfonsogarciacaro** [comment]
This should be fixed after updating the NUnit plugin :+1:
