### ISSUE TITLE
List.contains (and Seq.contains) is missing from Fable.Core

### ISSUE THREAD

**Issue by tomcl** [fsprojects/Fable#312]
### Description

As title. It confused me because the error message from Babel is opaque.

### Repro steps

compile
```
#r "node_modules/fable-core/Fable.Core.dll"
open Fable.Core
let okChar s = if List.contains s ['a';'b'] then "yes" else "no"
```
with `fable testFable.fsx`.

### Expected behavior

compiles successfully

### Actual behavior

```
ERROR: Object reference not set to an instance of an object. (C:\fable\tests\testfable.fsx)
```

### Known workarounds

Use `List.exists`, `Seq.exists`, etc

### Related information 

* Fable Version 0.4.6
* .NET Runtime
* W10

**Comment by alfonsogarciacaro** [comment]
Thanks for the report! This should be fixed with fable.compiler 0.5.0 and fable.core 0.5.0  :+1: Please feel free to reopen the issue if it still doesn't work for you.
