### ISSUE TITLE
Always Print Compiler Version During Compilation

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/Fable#323]
instead of 
```
Starting Compilation...
```

show

```
fable-compiler@0.5.2 : Starting Compilation...
```
It's a small change that should help alleviate confusion, especially when fable is a called as part of a build script/task where by default it isn't set to verbose.

**Comment by alfonsogarciacaro** [comment]
This is easy to implement, non-intrusive and very helpful. I'll implement it for the next release :+1:
