### ISSUE TITLE
Typescript2Fable - Anonymous objects in function parameters

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/Fable#33]
Anonymous objects (both objects and unions) defined in function signature are erased to object:

Input
``` 
export class Location {
    uri: Uri;
    range: Range;
    constructor(uri: Uri, rangeOrPosition: Range | Position);
}
```

Output:
```
type Location =
        abstract createNew: uri: Uri * rangeOrPosition: obj -> Location
        abstract uri: Uri with get, set
        abstract range: Range with get, set
```

Expected output option 1:
```
type RangeOrPosition = 
    | Range of Range
    | Position of Position

and Location =
    abstract createNew: uri: Uri * rangeOrPosition: RangeOrPosition -> Location
    abstract uri: Uri with get, set
    abstract range: Range with get, set
```

Expected output option 2:
```
and Location =
    abstract createNew: uri: Uri * rangeOrPosition: Range-> Location
    abstract createNew: uri: Uri * rangeOrPosition: Position-> Location
    abstract uri: Uri with get, set
    abstract range: Range with get, set
```

Option 1 is probably better as it can be also used for anonymous types not only unions

**Comment by Krzysztof-Cieslak** [comment]
It would be also very good if we could detect that same anonymous type is used somewhere else in definition file so we don't duplicate additionally generated types

**Comment by alfonsogarciacaro** [comment]
The issue has been fixed for union types with erased union types in F# (see [explanation](https://github.com/fsprojects/Fable/issues/4#issuecomment-184234507)). I'm not sure about other anonymous types: it's not trivial to translate them and also I didn't like in FunScript how the namespaces got polluted with anonymous types. My intention is not to create a perfect parser but something that makes most of the work and is easy to tweak by hand later. My priority now is to create samples and tutorials for the project so at the moment I'm happy with having ``obj`` replacing anonymous types. Of course, I would be happy to get a PR to fix this :)
