### ISSUE TITLE
add a preprocessor symbol to indicate FABLE compilation

### ISSUE THREAD

**Issue by tomcl** [fsprojects/Fable#331]
Would help writing code that is automatically portable between FABLE and FSC. Can do this anyway with com line symbols but this would make such functionality work out of the box.
Proposed symbol:

```
__FABLE_COMPILER__
```
(adjust underscores to be compatible with global conventions I probably don't know)

**Comment by forki** [comment]
Maybe it could add antoher symbol which gives version information. But not sure if that's practical.

**Comment by alfonsogarciacaro** [comment]
Given that Fable is evolving very quickly now, probably including version information won't be very practical indeed. In F# I think usually the double underscore is used for macros like `__SOURCE_DIRECTORY__`, but compilation symbols tend to be simpler (`INTERACTIVE`). Probably just `FABLE` would be **too** simple. `FABLE_COMPILER`?

**Comment by forki** [comment]
Yes I would go with FABLE_COMPILER

**Comment by tomcl** [comment]
`FABLE_COMPILER` is good with me.

However, I'd still wonder whether `_FABLE_COMPILER_` or `_FABLE_COMPILER` would be better with the underscores indicating system-level status. I defer to whatever others more familiar with F#/Javascript conventions think.
