### ISSUE TITLE
printf/sprintf "%A"

### ISSUE THREAD

**Issue by tomcl** [fsprojects/Fable#338]
### Description

Programs displaying cyclic data structures with "%A" format option will crash under FABLE.

This is mildly annoying because when porting code with debug printout the debug stuff crashes the code.

### Repro steps

This problem is known so no example is needed

### Suggestion for fix

I'm not myself familiar with Javascript so will not submit a PR. I have a suggestion for an easy fix, which is to use the Node function `util.inspect(object: <any>)`. This will provide debug printout for any object resolving cyclic structures. I'm not certain whether this dependency in the FABLE RTS would be an issue? If FABLE uses node anyway it would be fine.

**Comment by alfonsogarciacaro** [comment]
Fable uses node but only for development, so `util.inspect` won't work in a browser environment during runtime. I guess that a simple `try ... catch` with a minimal fallback (printing the key-value pairs of the object) should be enough, but please tell me otherwise.

**Comment by tomcl** [comment]
Yes, it is crashing on debug printout that is unpleasant, so that
      would be much better!
    Tom
    
    
    On 10/08/2016 17:32, Alfonso
      Garcia-Caro wrote:
    
    
      
      Fable uses node but only for development, so util.inspect
        won't work in a browser environment during runtime. I guess that
        a simple try ... catch with a minimal fallback
        (printing the key-value pairs of the object) should be enough,
        but please tell me otherwise.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
          
          
        
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fsprojects/Fable","title":"fsprojects/Fable","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fsprojects/Fable"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alfonsogarciacaro in #338: Fable uses node but only for development, so `util.inspect` won't work in a browser environment during runtime. I guess that a simple `try ... catch` with a minimal fallback (printing the key-value pairs of the object) should be enough, but please tell me otherwise."}],"action":{"name":"View Issue","url":"https://github.com/fsprojects/Fable/issues/338#issuecomment-238924089"}}}
