### ISSUE TITLE
Typescript2Fable - Enums

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsprojects/Fable#34]
At the moment enums are ignored (no types for them is generated) but names of enums types are used as function parameters.

Option 1. Erase enums to obj ( make alias type ENUM_TYPE = obj)
Option 2. Erase enums to ints ( make alias type ENUM_TYPE = int) - enums in TS are just ints under the hood, we could use that
Option 3. Create F# enum types
Option 4. Create F# class with static members for each enum case. 

To be fair, I would be happy enough with Option 2 for start and build better solution later on. I should be able to PR it, just let me know which solution you want to use.

**Comment by alfonsogarciacaro** [comment]
I think FunScript managed to translate TypeScript enums to F# `[<Enum>]`. It would be great to do that. I don't think it'll cause problems with Fable compiler as it's already converting .NET enums to int literals (this is actually done by F# compiler). It shouldn't be difficult, we only need to add a check for `EnumDeclaration` (see [sample](http://astexplorer.net/#/ZBT5MJbwEr)). If you want to send a PR that'd be awesome. I'll also try to have a look in the evening :)

**Comment by Krzysztof-Cieslak** [comment]
I'll be happy to work on it, will try to PR it today. AST explorer will be very helpful, thanks for link!  :)

**Comment by alfonsogarciacaro** [comment]
Yes, if it weren't for AST explore it would have been impossible for me to understand TypeScript AST ;) I wish it were as simple as F#'s!
