### ISSUE TITLE
Record type quotes

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fable#51]
It looks like for record types the `this.x=$arg0` are being wrapped in a quotes.

The following code:

```
type ElementBuilder = {
    TypeName: string
    Styles: (string * obj) list
}
```

emits this js:
```
  var ElementBuilder = Program.ElementBuilder = function () {
    function _class($arg0, $arg1) {
      _classCallCheck(this, _class);

      "this.TypeName=$arg0;this.Styles=$arg1";
    }

    return _class;
  }();
```

**Comment by alfonsogarciacaro** [comment]
Strange, this works fine for me both in Mac and Windows. Are you using the last code (I changed something about this recently)? If so, can you please post or link to the full code? Cheers!

**Comment by davidtme** [comment]
I've delete my repo and start again and everything seem to be working now.  Thanks
