### ISSUE TITLE
Build fails on Windows 32 bit

### ISSUE THREAD

**Issue by davidpodhola** [fsprojects/Fable#54]
Because the `node.js` nuget package is for 64-bit Windows only see https://github.com/giggio/bower-nuget/issues/10

In on of my branches I used different approach to find `node` and `npm` so will submit a PR.

**Comment by alfonsogarciacaro** [comment]
It would be nice to fix the issue but building the project is only needed for development. To use the compiler it will be enough to download it with `npm`, so this is not a priority at the moment. Please don't worry too much about it :)
