### ISSUE TITLE
(released) Fable compiler not usable on certain Windows machines (System.Numerics.dll)

### ISSUE THREAD

**Issue by davidpodhola** [fsprojects/Fable#58]
Seems like a reincarnation of https://github.com/fsprojects/Fable/issues/35

On some Windows machines `fable-compiler` is not working. I created the [repro repository](https://github.com/davidpodhola/fable-samples/tree/master/32bit).

![fable-not-working](https://cloud.githubusercontent.com/assets/436605/13718071/a10952a2-e7e6-11e5-82d4-cf917efd8631.PNG)

Might be related to .NET 4.6 (without .NET 4.5) installed, 32-bit Windows or no Visual Studio installed.

**Comment by alfonsogarciacaro** [comment]
To be moved to FSharp.Compiler.Services
