### ISSUE TITLE
(released) Fable compiler not usable on certain Windows machines (FSharp.Core.optdata)

### ISSUE THREAD

**Issue by davidpodhola** [fsprojects/Fable#59]
See screenshot below. Probably just [the `FSharp.Core.optdata` file needs to be included in the distribution](https://fsharp.github.io/FSharp.Compiler.Service/corelib.html#Do-I-need-to-include-FSharp-Core-optdata-and-FSharp-Core-sigdata).
I created the [repro repository](https://github.com/davidpodhola/fable-samples/tree/master/32bit).

![fable-not-working-fsharp core optdata](https://cloud.githubusercontent.com/assets/436605/13718482/b80dd8d4-e7ea-11e5-96ba-444acc4b9fda.PNG)

**Comment by davidpodhola** [comment]
Looking at it.

**Comment by alfonsogarciacaro** [comment]
Hi David, I really appreciate your efforts to make sure Fable runs on multiple machines. But unfortunately I'm afraid I cannot do much about the F# compiling itself here. Could you please report these issues in the FSharp.Compiler.Services repo instead? Thanks a ton!

**Comment by davidpodhola** [comment]
Taking the FSharp.Core.optdata and FSharp.Core.sigdata files really fixed this, but we end with #58 then.

**Comment by davidpodhola** [comment]
Hi @alfonsogarciacaro I know I am a little bit annoying, I know. The thing is the configurations are not corner-cases, they simply do not have F# or Visual Studio installed as happens a lot with my colleagues.
However you are totally right, they are related to [FSharp.Compiler.Services](http://fsharp.github.io/FSharp.Compiler.Service/), I will try to make smaller repos and report them there.

**Comment by alfonsogarciacaro** [comment]
To be moved to FSharp.Compiler.Services
