### ISSUE TITLE
Fable compiler should require specific Node.js engine version

### ISSUE THREAD

**Issue by davidpodhola** [fsprojects/Fable#60]
[Specify required version of node.js](https://docs.npmjs.com/files/package.json#engines) to make sure the compile would not fail (screenshot from [Ubuntu 14.04 running the node.js installed using Ubuntu Package Manager](http://www.hostingadvice.com/how-to/install-nodejs-ubuntu-14-04/#ubuntu-package-manager))

![fable-not-working-ubuntu](https://cloud.githubusercontent.com/assets/436605/13718871/97a3d22a-e7ee-11e5-9f4e-2c22d2d172d1.PNG)

**Comment by alfonsogarciacaro** [comment]
I have replaced the ES6 object literal method shortcuts which was causing this fail. To be honest, I'm not sure which is the minimum node version to run fable, but probably it will do with 4.x, I'll check later.

**Comment by alfonsogarciacaro** [comment]
The required engine version has been set to 4.4 which is the current node stable version. Thanks for the report!
