### ISSUE TITLE
Type and record property with the same name

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fable#62]
Again this could be a problem with FSharp.Compiler.Service

Consider the following code:
```
type StyleBuilderHelper =
    { TopOffset : int
      BottomOffset : int }
 
type DomBuilder =
    { ElementType : string
      StyleBuilderHelper : StyleBuilderHelper }
 
let offsetBottom size builder =
    { builder with StyleBuilderHelper =  { builder.StyleBuilderHelper with BottomOffset = size } }

```
The JavaScript generated has a problem in that StyleBuilderHelper is being used as the type name and a record property name:
```
var offsetBottom = Program.offsetBottom = function (size, builder) {
      var StyleBuilderHelper, inputRecord;
      return StyleBuilderHelper = (inputRecord = builder.StyleBuilderHelper, new StyleBuilderHelper(inputRecord.TopOffset, size)), new DomBuilder(builder.ElementType, StyleBuilderHelper);
    };

```
A undefined variable is created with the name ```StyleBuilderHelper``` then the type ``` StyleBuilderHelper``` tries to get constructed resulting in
```StyleBuilderHelper is not a function```

**Comment by alfonsogarciacaro** [comment]
I was afraid [something like this could happen](https://github.com/fsprojects/Fable/blob/master/src/fable-fsharp/Fable2Babel.fs#L435). I think it's not F# compiler's fault this time. Right now the variable scope starts from zero for every method, I need to pass the names of the members of the current module to prevent clashes like this.

Another solution would be to fully qualify the name of the members even within the same module. Modules are compiled as functions and get a self reference passed as an argument so this should be possible.

**Comment by davidtme** [comment]
Thanks for your comments, it’s an easy enough bug to work around at the moment now I know about it.
