### ISSUE TITLE
Suggestion: Units of Measure support

### ISSUE THREAD

**Issue by WorldMaker** [fsprojects/Fable#71]
One of the reasons I considered writing some code in F# and then transpiling it to Typescript or JS was I thought it would be great to get F#'s support for compile time units of measure checking, especially if it transpiled to also support any of the JS runtime units of measures libraries for some runtime security as well.

Maybe this would be useful functionality for Fable to attempt?

**Comment by alfonsogarciacaro** [comment]
Units of measure are supported but they're erased in runtime code. This is the same behaviour when [compiling F# to .NET](https://msdn.microsoft.com/en-us/library/dd233243.aspx#Anchor_4) so I'm not sure it would make sense to change this for Fable :/

**Comment by WorldMaker** [comment]
Yeah, I've wondered if F# should probably support deeper runtime support as an optional buy in... I would think any runtime support in JS would be optional, and I don't see a problem with maybe supporting options unavailable on the CLR.

**Comment by alfonsogarciacaro** [comment]
Well the biggest problems are maintenance and programmer's expectations. I think a developer can understand Fable doesn't support all F# features but if, at the same time, it adds some features on its own, things can get a bit messy. Also, Fable is sandwiched between F# compiler and Babel AST specs and adding non-standard features requires extra work which needs to be carefully considered beforehand.

All in all, I wouldn't deem this as a priority at the moment. However, we could reconsider this if other users request the feature. And of course, I would be more than happy to review a PR on the matter :)

**Comment by alfonsogarciacaro** [comment]
Closing this for now
