### ISSUE TITLE
Byte arrays mapped to Uint8ClampedArray

### ISSUE THREAD

**Issue by fdcastel** [fsprojects/Fable#77]
As discussed in #74, currently Byte arrays mapped to Uint8ClampedArray in JavaScript.

Should we add a compiler switch for this ? 

And, if yes, what should be the default? I'm asking because the clamped version appears to be the "ugly duckling" here:

https://github.com/fsprojects/Fable/blob/master/src/fable-fsharp/AST/AST.Fable.fs#L291

**Comment by alfonsogarciacaro** [comment]
I chose to have clamped array as the default because I imagined the usual scenario for using unsigned byte arrays would be manipulating canvas image data. But I agree that, if adding the switch, the default should be the option programmers expect, that is the non-clamped version.

I'm thinking of adding a `--clamped` flag which, when set, translates `ubyte[]` to `UInt8Clamped`. Would that suit your needs?

**Comment by fdcastel** [comment]
Sure! For me it's perfect. Just what the doctor ordered ;)

What about "--byteClamped"? A bit longer, but more informative​.

A negative point of this would be the breaking change. Maybe to put a little warning about it​? (Don't know how many users of this feature are out there).

**Comment by alfonsogarciacaro** [comment]
Yeah, I was worried about the flag not conveying all the information, but unfortunately ``--byteClamped`` isn't complete either :( I'd stick with something brief and add the complete information in the usage guide (which can be displayed with `fable -h`).

It will be a breaking change, but I'm currently preparing a new version with a few other (unfortunately necessary) breaking changes and (hopefully) there shouldn't be any Fable code in production yet so it should be fine. Actually the idea of releasing the beta soon was to get users' feedback and improve things before the RC. I promise to keep semantic versioning from 1.0.0 on :)

**Comment by alfonsogarciacaro** [comment]
`--clamp` flag option has been added. Depending on whether is checked or not, unsigned byte arrays will compile to Uint8Array or Uint8ClampedArray.

**Comment by fdcastel** [comment]
Nice! Gracias!
