### ISSUE TITLE
HashSet?

### ISSUE THREAD

**Issue by fdcastel** [fsprojects/Fable#78]
Any ideas on how to map a HashSet (System.Collections.Generic.HashSet) to JavaScript?

Should it be part of fable-core.js?

**Comment by alfonsogarciacaro** [comment]
Right now F# `Map` and `System.Collections.Generic.Dictionary` compile both to ES6 `Map` objects, the only difference is that adding and removing creates a new map when using immutable maps: 
https://github.com/fsprojects/Fable/blob/master/src/fable-fsharp/Replacements.fs#L587-L598

Probably we should do the same with F# `Set` and `HashSet`.

**Comment by fdcastel** [comment]
Nice! I'll take a look at it.
