### ISSUE TITLE
Enums comparison

### ISSUE THREAD

**Issue by fdcastel** [fsprojects/Fable#81]
`Cannot find replacement for Microsoft.FSharp.Core.Operators.>=` when comparing enums.

The expression 

`1 >= 2`

Has the following ApplyInfo:

```
{methodName = ">=";
 ownerFullName = "Microsoft.FSharp.Core.Operators";
 callee = null;
 args =
  [Value (NumberConst (Case1 1,Int32)); Value (NumberConst (Case1 2,Int32))];
 returnType = PrimitiveType Boolean;
 decorators = [];
 calleeTypeArgs = [];
 methodTypeArgs = [PrimitiveType (Number Int32)];}
```

Which is fine. However, the same expression using enums

`MyEnum.A >= MyEnum.B`

where

```
type MyEnum = 
| A = 0x20uy
| B = 0x50uy
```

produces

```
{methodName = ">=";
 ownerFullName = "Microsoft.FSharp.Core.Operators";
 callee = null;
 args =
  [Wrapped
     (Value (NumberConst (Case1 32,UInt8Clamped)),DeclaredType MyEnum Class null);
   Wrapped
     (Value (NumberConst (Case1 80,UInt8Clamped)),DeclaredType MyEnum Class null)];
 returnType = PrimitiveType Boolean;
 decorators = [];
 calleeTypeArgs = [];
 methodTypeArgs = [DeclaredType MyEnum Class null];}
```

Which fails the 'compare' function of Replacements.fs

Suggestions? ;)

BTW: I'm adding more functions to support enums (https://github.com/fdcastel/Fable/commit/b7ab040beb3f6df776d86194536817d6143eb581), but not enough to make a PR, yet.

**Comment by alfonsogarciacaro** [comment]
Good catch! Actually there's no obvious way right now to tell enums apart in Fable's internal AST, maybe we should add it.

Or, as the enum type is just "wrapped" around the integer, the current solution would be to change the [first lines of `Replacements.compare`](https://github.com/fsprojects/Fable/blob/master/src/fable-fsharp/Replacements.fs#L177-L185) as follows (I haven't tested it yet but it should work):

```fsharp
    let compare com (i: Fable.ApplyInfo) (args: Fable.Expr list) op =
        let op = Fable.BinaryOp op |> Fable.Value
        match args.Head with
        | Type Fable.UnknownType
        | Type (Fable.PrimitiveType _)  // TODO: Array comparison?
        | Fable.Wrapped (Type (Fable.PrimitiveType _), _)
        | Type (FullName "System.TimeSpan")
        | Type (FullName "System.DateTime") ->
            Fable.Apply(op, args, Fable.ApplyMeth, i.returnType, i.range) |> Some
        | Type (Fable.DeclaredType ent) ->
```

If you agree with this solution, could you please add it your PR? Thanks!

**Comment by fdcastel** [comment]
Sure! I'll take care of it.  Thanks, man!

**Comment by fdcastel** [comment]
Done! Your suggestion worked perfectly, but I had to make a little change to handle comparisons between wrapped and non-wrapped values.

The samples I provided were only with literals (`MyEnum.A`, `MyEnum.B`) which are both wrapped. However, when comparing a value with a literal (`a >= MyEnum.B`) the problem occurred (but not if comparing a literal against a value, i.e., `MyEnum.B >= a`).

I added a few tests to catch this in the future. ;) 

Please review it. If it's all fine, we can close this. :+1:
